# Generated by Claude Sonnet 4.5 on 2026-03-02
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Button
import logging
import time

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    datefmt='%H:%M:%S'
)
logger = logging.getLogger(__name__)

# Global parameters
params = {
    'xmin': -2.0, 'xmax': 2.0,
    'ymin': -2.5, 'ymax': 2.5,
    'width': 1024, 'height': 1024,
    'max_iter': 10
}

def calculate_mandelbrot(xmin, xmax, ymin, ymax, width, height, max_iter):
    """Calculate the Mandelbrot set for given parameters"""
    start_time = time.time()
    logger.info(f"Starting calculation: {width}x{height} pixels, {max_iter} iterations")
    logger.info(f"Region: Re[{xmin:.6f}, {xmax:.6f}], Im[{ymin:.6f}, {ymax:.6f}]")
    
    # Create grid of complex numbers
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    c = X + 1j * Y
    
    # Initialize z and output array
    z = np.zeros_like(c)  # Start with z=0 for all points
    output = np.zeros(c.shape, dtype=int)  # Will store iteration count when each point escapes
    
    # Iterate the Mandelbrot formula: z = z^2 + c
    for n in range(max_iter):
        mask = np.abs(z) <= 2  # Points still bounded (haven't escaped yet)
        z[mask] = z[mask] ** 2 + c[mask]  # Apply formula only to non-escaped points
        output[mask & (np.abs(z) > 2) & (output == 0)] = n  # Record iteration count when point first escapes
    
    # Points that never escaped (stayed bounded) get max_iter value - these form the Mandelbrot set
    output[output == 0] = max_iter
    
    elapsed_time = time.time() - start_time
    logger.info(f"Calculation completed in {elapsed_time:.3f} seconds")
    logger.info("-" * 60)
    
    return output

def update_plot():
    """Recalculate and update the plot"""
    output = calculate_mandelbrot(
        params['xmin'], params['xmax'], 
        params['ymin'], params['ymax'],
        params['width'], params['height'], 
        params['max_iter']
    )
    
    im.set_data(output)
    im.set_extent([params['xmin'], params['xmax'], params['ymin'], params['ymax']])
    im.set_clim(0, params['max_iter'])
    ax.set_title(f'Mandelbrot Set (Iterations: {params["max_iter"]})')
    fig.canvas.draw_idle()

def zoom_in(event):
    """Zoom in by 2x and increase iterations by 10"""
    xcenter = (params['xmin'] + params['xmax']) / 2
    ycenter = (params['ymin'] + params['ymax']) / 2
    xrange = (params['xmax'] - params['xmin']) / 4
    yrange = (params['ymax'] - params['ymin']) / 4
    
    params['xmin'] = xcenter - xrange
    params['xmax'] = xcenter + xrange
    params['ymin'] = ycenter - yrange
    params['ymax'] = ycenter + yrange
    params['max_iter'] += 10
    
    update_plot()

def zoom_out(event):
    """Zoom out by 2x and decrease iterations by 10"""
    xcenter = (params['xmin'] + params['xmax']) / 2
    ycenter = (params['ymin'] + params['ymax']) / 2
    xrange = (params['xmax'] - params['xmin'])
    yrange = (params['ymax'] - params['ymin'])
    
    params['xmin'] = xcenter - xrange
    params['xmax'] = xcenter + xrange
    params['ymin'] = ycenter - yrange
    params['ymax'] = ycenter + yrange
    params['max_iter'] = max(10, params['max_iter'] - 10)  # Don't go below 10
    
    update_plot()

def reset_view(event):
    """Reset to initial view"""
    params['xmin'], params['xmax'] = -2.0, 2.0
    params['ymin'], params['ymax'] = -2.5, 2.5
    params['max_iter'] = 10
    update_plot()

def on_click(event):
    """Zoom to clicked location"""
    if event.inaxes == ax and event.button == 1:  # Left click on main axes
        # Get click coordinates
        cx, cy = event.xdata, event.ydata
        xrange = (params['xmax'] - params['xmin']) / 4
        yrange = (params['ymax'] - params['ymin']) / 4
        
        params['xmin'] = cx - xrange
        params['xmax'] = cx + xrange
        params['ymin'] = cy - yrange
        params['ymax'] = cy + yrange
        params['max_iter'] += 10
        
        update_plot()

# Create figure and initial plot
fig, ax = plt.subplots(figsize=(10, 9))
plt.subplots_adjust(bottom=0.15)

output = calculate_mandelbrot(
    params['xmin'], params['xmax'], 
    params['ymin'], params['ymax'],
    params['width'], params['height'], 
    params['max_iter']
)

im = ax.imshow(output, extent=[params['xmin'], params['xmax'], params['ymin'], params['ymax']], cmap='hot')
ax.set_xlabel('Re')
ax.set_ylabel('Im')
ax.set_title(f'Mandelbrot Set (Iterations: {params["max_iter"]})')
plt.colorbar(im, ax=ax, label='Iterations')

# Create buttons
ax_zoom_in = plt.axes([0.2, 0.05, 0.15, 0.05])
ax_zoom_out = plt.axes([0.4, 0.05, 0.15, 0.05])
ax_reset = plt.axes([0.6, 0.05, 0.15, 0.05])

btn_zoom_in = Button(ax_zoom_in, 'Zoom In (+10 iter)')
btn_zoom_out = Button(ax_zoom_out, 'Zoom Out (-10 iter)')
btn_reset = Button(ax_reset, 'Reset')

btn_zoom_in.on_clicked(zoom_in)
btn_zoom_out.on_clicked(zoom_out)
btn_reset.on_clicked(reset_view)

# Enable click-to-zoom
fig.canvas.mpl_connect('button_press_event', on_click)

plt.show()

