# Generated by GPT-4.1 on 2026-02-09
"""
Exercise 1.1: Use of registers
Implementations for calculating the difference between consecutive elements in X.
"""

import random
import time
import numpy as np

N = int(1e8)  # Adjust N for your computer speed

# 1. Python lists, regular for loop
X_list = [random.random() for _ in range(N)]
start = time.time()
Y_list = [X_list[i+1] - X_list[i] for i in range(N-1)]
end = time.time()
print(f"List for loop: {end-start:.4f} seconds")

# 2. Python lists, intermediate variables
start = time.time()
Y_list2 = []
for i in range(N-1):
    x_now = X_list[i]
    x_next = X_list[i+1]
    Y_list2.append(x_next - x_now)
end = time.time()
print(f"List for loop w/ vars: {end-start:.4f} seconds")

# 3. NumPy arrays, regular for loop
X_np = np.array(X_list)
start = time.time()
Y_np = np.empty(N-1)
for i in range(N-1):
    Y_np[i] = X_np[i+1] - X_np[i]
end = time.time()
print(f"NumPy for loop: {end-start:.4f} seconds")

# 4. NumPy arrays, intermediate variables
start = time.time()
Y_np2 = np.empty(N-1)
for i in range(N-1):
    x_now = X_np[i]
    x_next = X_np[i+1]
    Y_np2[i] = x_next - x_now
end = time.time()
print(f"NumPy for loop w/ vars: {end-start:.4f} seconds")

# 5. NumPy diff (vectorized)
start = time.time()
Y_diff = np.diff(X_np)
end = time.time()
print(f"NumPy diff: {end-start:.4f} seconds")