# Generated by Claude Sonnet 4.6 on 2026-04-04
"""
Dask Distributed implementation of Mandelbrot set computation.

Cluster layout assumptions:
  - dask-head  : runs the scheduler  (dask scheduler --port 8786)
  - worker VMs : each runs           (dask worker tcp://dask-head:8786)

Start the scheduler before running this script:
    dask scheduler --port 8786 --dashboard-address :8787

Start workers on each worker VM (after snapshotting):
    dask worker tcp://dask-head:8786 --nthreads 1 --nworkers auto

Then run this script from dask-head:
    cd ~/aau-ce2-nsc/miniproject_2
    python dask_distributed_implementation.py
"""

import time
import csv
import numpy as np
import dask.array as da
from distributed import Client, as_completed

from config import XMIN, XMAX, YMIN, YMAX, MAX_ITER, RESOLUTION_RAMP_UP, RESULT_DIR
from miniproject_1 import numpy_implementation, export_to_csv, visualize
from dask_implementation import dask_implementation_chunked

# ── Scheduler address ────────────────────────────────────────────────────────
SCHEDULER_ADDRESS = "tcp://dask-head:8786"
# ─────────────────────────────────────────────────────────────────────────────


# ---------------------------------------------------------------------------
# Core computation helper (must be importable on every worker node)
# ---------------------------------------------------------------------------

def _mandelbrot_chunk(c_chunk: np.ndarray, max_iter: int) -> np.ndarray:
    """Compute Mandelbrot iteration counts for a 2-D chunk of complex values."""
    z = np.zeros_like(c_chunk)
    output = np.zeros(c_chunk.shape, dtype=np.int32)
    for n in range(max_iter):
        mask = np.abs(z) <= 2
        if not mask.any():
            break
        z[mask] = z[mask] ** 2 + c_chunk[mask]
        output[mask] = n + 1
    return output


# ---------------------------------------------------------------------------
# Distributed implementations
# ---------------------------------------------------------------------------

def distributed_map_blocks(
    client: Client,
    xmin: float, xmax: float,
    ymin: float, ymax: float,
    width: int, height: int,
    max_iter: int,
    chunk_size: int = 256,
) -> np.ndarray:
    """
    Use dask.array.map_blocks submitted through a Distributed client.

    The whole dask graph is computed by the connected cluster, so each
    chunk lands on a different worker process automatically.
    """
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    c = (X + 1j * Y).astype(np.complex128)

    c_dask = da.from_array(c, chunks=(chunk_size, chunk_size))

    result = da.map_blocks(
        _mandelbrot_chunk,
        c_dask,
        dtype=np.int32,
        max_iter=max_iter,        # passed as kwarg to the function
    )

    # client.compute returns a Future; .result() blocks until done
    return client.compute(result).result()


def distributed_futures(
    client: Client,
    xmin: float, xmax: float,
    ymin: float, ymax: float,
    width: int, height: int,
    max_iter: int,
    chunk_size: int = 256,
) -> np.ndarray:
    """
    Manually scatter chunks as Futures using client.submit.

    Each row-slice of `chunk_size` rows is sent as an independent task,
    giving explicit control over task granularity.
    """
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    c = (X + 1j * Y).astype(np.complex128)

    # Split into row chunks
    row_slices = range(0, height, chunk_size)
    futures = {}
    for row_start in row_slices:
        row_end = min(row_start + chunk_size, height)
        c_chunk = c[row_start:row_end, :]
        futures[row_start] = client.submit(_mandelbrot_chunk, c_chunk, max_iter)

    # Collect results in order
    output = np.empty((height, width), dtype=np.int32)
    for row_start, future in futures.items():
        row_end = min(row_start + chunk_size, height)
        output[row_start:row_end, :] = future.result()

    return output


# ---------------------------------------------------------------------------
# Benchmarking
# ---------------------------------------------------------------------------

def benchmark_distributed(
    client: Client,
    resolutions=None,
    chunk_sizes=None,
    num_runs: int = 3,
):
    """
    Benchmark both distributed strategies against NumPy.

    Returns a list of tuples:
        (implementation, resolution, chunk_size, avg_time, std_time)
    """
    if resolutions is None:
        resolutions = RESOLUTION_RAMP_UP
    if chunk_sizes is None:
        chunk_sizes = [128, 256, 512]

    results = []

    print("=" * 70)
    print(f"Dask Distributed Benchmark  –  workers: {len(client.scheduler_info()['workers'])}")
    print("=" * 70)

    for res in resolutions:
        print(f"\n--- Resolution: {res}x{res} ---")

        # NumPy baseline
        numpy_times = []
        for _ in range(num_runs):
            t0 = time.perf_counter()
            numpy_implementation(XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER)
            numpy_times.append(time.perf_counter() - t0)
        np_avg, np_std = float(np.mean(numpy_times)), float(np.std(numpy_times))
        results.append(("NumPy", res, "N/A", np_avg, np_std))
        print(f"  NumPy                  : {np_avg:.4f}s ± {np_std:.4f}s")

        for chunk_size in chunk_sizes:
            if chunk_size > res:
                continue

            # map_blocks strategy
            mb_times = []
            for _ in range(num_runs):
                t0 = time.perf_counter()
                distributed_map_blocks(
                    client, XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER, chunk_size
                )
                mb_times.append(time.perf_counter() - t0)
            mb_avg, mb_std = float(np.mean(mb_times)), float(np.std(mb_times))
            speedup_mb = np_avg / mb_avg
            results.append(("Distributed-MapBlocks", res, chunk_size, mb_avg, mb_std))
            print(f"  map_blocks chunk={chunk_size:4d}  : {mb_avg:.4f}s ± {mb_std:.4f}s  "
                  f"(speedup {speedup_mb:.2f}x)")

            # futures strategy
            fut_times = []
            for _ in range(num_runs):
                t0 = time.perf_counter()
                distributed_futures(
                    client, XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER, chunk_size
                )
                fut_times.append(time.perf_counter() - t0)
            fut_avg, fut_std = float(np.mean(fut_times)), float(np.std(fut_times))
            speedup_fut = np_avg / fut_avg
            results.append(("Distributed-Futures", res, chunk_size, fut_avg, fut_std))
            print(f"  futures    chunk={chunk_size:4d}  : {fut_avg:.4f}s ± {fut_std:.4f}s  "
                  f"(speedup {speedup_fut:.2f}x)")

    return results


def save_results(results, filename: str):
    """Save benchmark results to CSV."""
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Implementation", "Resolution", "Chunk_Size", "Avg_Time", "Std_Time"])
        writer.writerows(results)
    print(f"\nResults saved to {filename}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import multiprocessing

    print(f"Connecting to Dask scheduler at {SCHEDULER_ADDRESS} …")
    # Set timeout so we get a clear error if the scheduler is not yet running
    client = Client(SCHEDULER_ADDRESS, timeout="30s")
    print(client)
    print(f"Dashboard : {client.dashboard_link}")
    print()

    RESOLUTIONS = RESOLUTION_RAMP_UP
    CHUNK_SIZES  = [128, 256, 512]
    NUM_RUNS     = 3

    results = benchmark_distributed(
        client,
        resolutions=RESOLUTIONS,
        chunk_sizes=CHUNK_SIZES,
        num_runs=NUM_RUNS,
    )

    save_results(results, f"{RESULT_DIR}/distributed_benchmark.csv")

    # ── Quick correctness check ──────────────────────────────────────────
    print("\nRunning correctness check (256x256) …")
    ref  = numpy_implementation(XMIN, XMAX, YMIN, YMAX, 256, 256, MAX_ITER)
    dist = distributed_map_blocks(client, XMIN, XMAX, YMIN, YMAX, 256, 256, MAX_ITER, 64)
    match = np.allclose(ref, dist)
    print(f"  NumPy vs Distributed match: {match}")

    client.close()
    print("\nDone.")
