# Generated by Claude Sonnet 4.6 on 2026-04-04
"""
Dask Distributed implementation of Mandelbrot set computation.

Cluster layout assumptions:
  - dask-head  : runs the scheduler  (dask scheduler --port 8786)
  - worker VMs : each runs           (dask worker tcp://dask-head:8786)

Start the scheduler before running this script:
    dask scheduler --port 8786 --dashboard-address :8787

Start workers on each worker VM (after snapshotting):
    dask worker tcp://dask-head:8786 --nthreads 1 --nworkers auto

Then run this script from dask-head:
    cd ~/aau-ce2-nsc/miniproject_2
    python dask_distributed_implementation.py
"""

import time
import csv
import dask
import numpy as np
import dask.array as da
import matplotlib.pyplot as plt
from distributed import Client

from config import XMIN, XMAX, YMIN, YMAX, MAX_ITER, RESOLUTION_RAMP_UP, RESULT_DIR, SCHEDULER_ADDRESS
from miniproject_1 import numpy_implementation, export_to_csv, visualize


def _mandelbrot_chunk(c_chunk: np.ndarray, max_iter: int) -> np.ndarray:
    """Pure-NumPy Mandelbrot kernel — defined here so it can be serialized to workers."""
    z = np.zeros_like(c_chunk)
    output = np.zeros(c_chunk.shape, dtype=np.int32)
    for n in range(max_iter):
        mask = np.abs(z) <= 2
        if not mask.any():
            break
        z[mask] = z[mask] ** 2 + c_chunk[mask]
        output[mask] = n + 1
    return output


def _compute_subregion(xmin, xmax, ymin, ymax, width, height, max_iter):
    """
    Compute Mandelbrot for a subregion from scalar bounds only.
    No numpy arrays are received — the worker builds its own grid,
    avoiding cross-version numpy/python serialisation issues.
    """
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    c = (X + 1j * Y).astype(np.complex128)
    z = np.zeros_like(c)
    output = np.zeros(c.shape, dtype=np.int32)
    for n in range(max_iter):
        mask = np.abs(z) <= 2
        if not mask.any():
            break
        z[mask] = z[mask] ** 2 + c[mask]
        output[mask] = n + 1
    return output




# ---------------------------------------------------------------------------
# Distributed implementations
# ---------------------------------------------------------------------------

def distributed_map_blocks(
    client: Client,
    xmin: float, xmax: float,
    ymin: float, ymax: float,
    width: int, height: int,
    max_iter: int,
    chunk_size: int = 256,
) -> np.ndarray:
    """
    Build the result as a large Dask array assembled from da.from_delayed blocks.
    Each block is a delayed call to _compute_subregion with scalar bounds only —
    no numpy arrays are serialised from head to workers, avoiding cross-version
    pickling issues. The result is a proper Dask array until client.compute().
    """
    x_scale = (xmax - xmin) / width
    y_scale = (ymax - ymin) / height

    rows = []
    for row in range(0, height, chunk_size):
        ch = min(chunk_size, height - row)
        row_blocks = []
        for col in range(0, width, chunk_size):
            cw = min(chunk_size, width - col)
            r_xmin = xmin + col * x_scale
            r_xmax = xmin + (col + cw) * x_scale
            r_ymin = ymin + row * y_scale
            r_ymax = ymin + (row + ch) * y_scale
            block = da.from_delayed(
                dask.delayed(_compute_subregion)(r_xmin, r_xmax, r_ymin, r_ymax, cw, ch, max_iter),
                shape=(ch, cw),
                dtype=np.int32,
            )
            row_blocks.append(block)
        rows.append(da.concatenate(row_blocks, axis=1))

    result_dask = da.concatenate(rows, axis=0)
    return client.compute(result_dask).result()


def distributed_futures(
    client: Client,
    xmin: float, xmax: float,
    ymin: float, ymax: float,
    width: int, height: int,
    max_iter: int,
    chunk_size: int = 256,
) -> np.ndarray:
    """
    Submit each row-slice as an explicit Future via client.submit.
    Only scalar bounds are sent; each worker builds its own subarray.
    """
    y_scale = (ymax - ymin) / height

    futures = {}
    for row in range(0, height, chunk_size):
        ch = min(chunk_size, height - row)
        r_ymin = ymin + row * y_scale
        r_ymax = ymin + (row + ch) * y_scale
        futures[row] = (ch, client.submit(_compute_subregion, xmin, xmax, r_ymin, r_ymax, width, ch, max_iter))

    output = np.empty((height, width), dtype=np.int32)
    for row, (ch, future) in futures.items():
        output[row:row + ch, :] = future.result()
    return output


# ---------------------------------------------------------------------------
# Benchmarking
# ---------------------------------------------------------------------------

def benchmark_distributed(
    client: Client,
    resolutions=None,
    chunk_sizes=None,
    num_runs: int = 3,
):
    """
    Benchmark both distributed strategies against NumPy.

    Returns a list of tuples:
        (implementation, resolution, chunk_size, avg_time, std_time)
    """
    if resolutions is None:
        resolutions = RESOLUTION_RAMP_UP
    if chunk_sizes is None:
        chunk_sizes = [128, 256, 512]

    results = []

    print("=" * 70)
    print(f"Dask Distributed Benchmark  –  workers: {len(client.scheduler_info()['workers'])}")
    print("=" * 70)

    for res in resolutions:
        print(f"\n--- Resolution: {res}x{res} ---")

        # NumPy baseline
        numpy_times = []
        for _ in range(num_runs):
            t0 = time.perf_counter()
            numpy_implementation(XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER)
            numpy_times.append(time.perf_counter() - t0)
        np_avg, np_std = float(np.mean(numpy_times)), float(np.std(numpy_times))
        results.append(("NumPy", res, "N/A", np_avg, np_std))
        print(f"  NumPy                  : {np_avg:.4f}s ± {np_std:.4f}s")

        for chunk_size in chunk_sizes:
            if chunk_size > res:
                continue

            # map_blocks strategy
            mb_times = []
            for _ in range(num_runs):
                t0 = time.perf_counter()
                distributed_map_blocks(
                    client, XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER, chunk_size
                )
                mb_times.append(time.perf_counter() - t0)
            mb_avg, mb_std = float(np.mean(mb_times)), float(np.std(mb_times))
            speedup_mb = np_avg / mb_avg
            results.append(("Distributed-MapBlocks", res, chunk_size, mb_avg, mb_std))
            print(f"  map_blocks chunk={chunk_size:4d}  : {mb_avg:.4f}s ± {mb_std:.4f}s  "
                  f"(speedup {speedup_mb:.2f}x)")

            # futures strategy
            fut_times = []
            for _ in range(num_runs):
                t0 = time.perf_counter()
                distributed_futures(
                    client, XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER, chunk_size
                )
                fut_times.append(time.perf_counter() - t0)
            fut_avg, fut_std = float(np.mean(fut_times)), float(np.std(fut_times))
            speedup_fut = np_avg / fut_avg
            results.append(("Distributed-Futures", res, chunk_size, fut_avg, fut_std))
            print(f"  futures    chunk={chunk_size:4d}  : {fut_avg:.4f}s ± {fut_std:.4f}s  "
                  f"(speedup {speedup_fut:.2f}x)")

    return results


def plot_results(results, save_path: str):
    """Plot execution time and speedup for distributed benchmark results."""
    numpy_results = {r[1]: r[3] for r in results if r[0] == "NumPy"}
    resolutions = sorted(numpy_results.keys())

    strategies = {}
    for r in results:
        if r[0] == "NumPy":
            continue
        key = f"{r[0]} chunk={r[2]}"
        strategies.setdefault(key, []).append((r[1], r[3]))

    fig, axes = plt.subplots(1, 2, figsize=(15, 6))
    fig.suptitle("Dask Distributed Benchmark", fontsize=14)

    # — Execution time —
    axes[0].plot(resolutions, [numpy_results[r] for r in resolutions],
                 "o-", linewidth=2, markersize=8, label="NumPy baseline")
    for label, data in sorted(strategies.items()):
        data.sort()
        axes[0].plot([d[0] for d in data], [d[1] for d in data],
                     "s--", linewidth=1.5, markersize=5, label=label)
    axes[0].set_xlabel("Resolution")
    axes[0].set_ylabel("Execution Time (s)")
    axes[0].set_title("Execution Time")
    axes[0].set_yscale("log")
    axes[0].legend(fontsize=7)
    axes[0].grid(True, alpha=0.3, which="both")

    # — Speedup vs NumPy —
    for label, data in sorted(strategies.items()):
        data.sort()
        speedups = [(res, numpy_results[res] / t) for res, t in data if res in numpy_results]
        axes[1].plot([s[0] for s in speedups], [s[1] for s in speedups],
                     "s-", linewidth=1.5, markersize=5, label=label)
    axes[1].axhline(y=1, color="r", linestyle="--", alpha=0.5, label="NumPy baseline")
    axes[1].set_xlabel("Resolution")
    axes[1].set_ylabel("Speedup (vs NumPy)")
    axes[1].set_title("Speedup")
    axes[1].legend(fontsize=7)
    axes[1].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(save_path, dpi=150)
    plt.close()
    print(f"Plot saved to {save_path}")


def save_results(results, filename: str):
    """Save benchmark results to CSV."""
    with open(filename, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Implementation", "Resolution", "Chunk_Size", "Avg_Time", "Std_Time"])
        writer.writerows(results)
    print(f"\nResults saved to {filename}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print(f"Connecting to Dask scheduler at {SCHEDULER_ADDRESS} …")
    # Set timeout so we get a clear error if the scheduler is not yet running
    client = Client(SCHEDULER_ADDRESS, timeout="30s")
    print(client)
    print(f"Dashboard : {client.dashboard_link}")
    print()

    RESOLUTIONS = RESOLUTION_RAMP_UP
    CHUNK_SIZES  = [128, 256, 512]
    NUM_RUNS     = 3

    results = benchmark_distributed(
        client,
        resolutions=RESOLUTIONS,
        chunk_sizes=CHUNK_SIZES,
        num_runs=NUM_RUNS,
    )

    save_results(results, f"{RESULT_DIR}/distributed_benchmark.csv")
    plot_results(results, f"{RESULT_DIR}/distributed_benchmark.png")

    # ── Quick correctness check ──────────────────────────────────────────
    print("\nRunning correctness check (256x256) …")
    ref  = numpy_implementation(XMIN, XMAX, YMIN, YMAX, 256, 256, MAX_ITER)
    dist = distributed_map_blocks(client, XMIN, XMAX, YMIN, YMAX, 256, 256, MAX_ITER, 64)
    match = np.allclose(ref, dist)
    print(f"  NumPy vs Distributed match: {match}")

    client.close()
    print("\nDone.")
