# Generated by Claude Sonnet 4.6 on 2026-04-06
"""
Dask implementation of Mandelbrot set computation.
Compares multi-core Dask execution with NumPy vectorized implementation.
"""

import time
import numpy as np
import dask.array as da
import matplotlib.pyplot as plt

from config import XMIN, XMAX, YMIN, YMAX, MAX_ITER, RESOLUTION_RAMP_UP, RESULT_DIR
from miniproject_1 import numpy_implementation, export_to_csv, visualize


def _mandelbrot_chunk(c_chunk: np.ndarray, max_iter: int) -> np.ndarray:
    """Pure-NumPy Mandelbrot kernel for one chunk of the complex plane."""
    z = np.zeros_like(c_chunk)
    output = np.zeros(c_chunk.shape, dtype=np.int32)
    for n in range(max_iter):
        mask = np.abs(z) <= 2
        if not mask.any():
            break
        z[mask] = z[mask] ** 2 + c_chunk[mask]
        output[mask] = n + 1
    return output


def dask_implementation(xmin, xmax, ymin, ymax, width, height, max_iter, chunk_size=256):
    """
    Compute Mandelbrot set using Dask arrays and map_blocks.

    The complex-plane grid is built with NumPy, wrapped in a Dask array,
    and map_blocks distributes each chunk to a worker. The result stays as
    a Dask array until .compute() — no manual reassembly needed.
    """
    x = np.linspace(xmin, xmax, width)
    y = np.linspace(ymin, ymax, height)
    X, Y = np.meshgrid(x, y)
    c = (X + 1j * Y).astype(np.complex128)

    c_dask = da.from_array(c, chunks=(chunk_size, chunk_size))
    result = da.map_blocks(_mandelbrot_chunk, c_dask, dtype=np.int32, max_iter=max_iter)
    return result.compute()


def benchmark_dask_vs_numpy(resolutions=None, chunk_sizes=None, num_runs=3):
    """
    Benchmark Dask implementation against NumPy.

    Args:
        resolutions: List of resolutions to test
        chunk_sizes: List of chunk sizes for Dask
        num_runs: Number of runs per configuration

    Returns:
        List of benchmark results
    """
    if resolutions is None:
        resolutions = RESOLUTION_RAMP_UP
    
    if chunk_sizes is None:
        chunk_sizes = [64, 128, 256, 512]
    
    results = []
    
    print("=" * 70)
    print("Benchmarking Dask vs NumPy Mandelbrot Implementation")
    print("=" * 70)
    
    for res in resolutions:
        print(f"\n--- Resolution: {res}x{res} ---")
        
        # Benchmark NumPy
        numpy_times = []
        for _ in range(num_runs):
            start = time.perf_counter()
            _ = numpy_implementation(XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER)
            numpy_times.append(time.perf_counter() - start)
        
        numpy_avg = np.mean(numpy_times)
        numpy_std = np.std(numpy_times)
        results.append(("NumPy", res, "N/A", numpy_avg, numpy_std))
        print(f"NumPy:              {numpy_avg:.4f}s ± {numpy_std:.4f}s")
        
        # Benchmark Dask with different chunk sizes
        for chunk_size in chunk_sizes:
            if chunk_size > res:
                continue
                
            dask_times = []
            for _ in range(num_runs):
                start = time.perf_counter()
                _ = dask_implementation(
                    XMIN, XMAX, YMIN, YMAX, res, res, MAX_ITER, chunk_size
                )
                dask_times.append(time.perf_counter() - start)
            
            dask_avg = np.mean(dask_times)
            dask_std = np.std(dask_times)
            speedup = numpy_avg / dask_avg
            
            results.append(("Dask", res, chunk_size, dask_avg, dask_std))
            print(f"Dask (chunk={chunk_size:3d}):   {dask_avg:.4f}s ± {dask_std:.4f}s  "
                  f"(speedup: {speedup:.2f}x)")
    
    return results


def plot_comparison(results, save_path=None):
    """Plot comparison between Dask and NumPy results."""
    # Separate NumPy and Dask results
    numpy_results = [(r[1], r[3]) for r in results if r[0] == "NumPy"]
    dask_results = {}
    
    for r in results:
        if r[0] == "Dask":
            chunk_size = r[2]
            if chunk_size not in dask_results:
                dask_results[chunk_size] = []
            dask_results[chunk_size].append((r[1], r[3]))
    
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    
    # Plot 1: Execution time comparison
    resolutions = [r[0] for r in numpy_results]
    numpy_times = [r[1] for r in numpy_results]
    
    axes[0].plot(resolutions, numpy_times, 'o-', linewidth=2, markersize=8, label='NumPy')
    
    for chunk_size, data in sorted(dask_results.items()):
        data.sort()
        res = [d[0] for d in data]
        times = [d[1] for d in data]
        axes[0].plot(res, times, 's--', linewidth=2, markersize=6, 
                    label=f'Dask (chunk={chunk_size})')
    
    axes[0].set_xlabel('Resolution')
    axes[0].set_ylabel('Execution Time (seconds)')
    axes[0].set_title('Dask vs NumPy Execution Time')
    axes[0].set_yscale('log')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3, which='both')
    
    # Plot 2: Speedup relative to NumPy
    for chunk_size, data in sorted(dask_results.items()):
        data.sort()
        speedups = []
        res_list = []
        for res, dask_time in data:
            numpy_time = next(t for r, t in numpy_results if r == res)
            speedups.append(numpy_time / dask_time)
            res_list.append(res)
        
        axes[1].plot(res_list, speedups, 's-', linewidth=2, markersize=6,
                    label=f'chunk={chunk_size}')
    
    axes[1].axhline(y=1, color='r', linestyle='--', alpha=0.5, label='NumPy baseline')
    axes[1].set_xlabel('Resolution')
    axes[1].set_ylabel('Speedup (vs NumPy)')
    axes[1].set_title('Dask Speedup Relative to NumPy')
    axes[1].legend()
    axes[1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path, dpi=150)
        print(f"\nPlot saved to {save_path}")
    
    plt.show()


def save_results(results, filename):
    """Save benchmark results to CSV."""
    import csv
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['Implementation', 'Resolution', 'Chunk_Size', 'Avg_Time', 'Std_Time'])
        writer.writerows(results)
    print(f"Results saved to {filename}")


if __name__ == "__main__":
    import multiprocessing as mp
    
    print(f"System has {mp.cpu_count()} CPU cores")
    print()
    
    # Configuration
    RESOLUTIONS = RESOLUTION_RAMP_UP  # Test all resolutions
    CHUNK_SIZES = [64, 128, 256, 512]
    NUM_RUNS = 3
    
    # Run benchmark
    results = benchmark_dask_vs_numpy(
        resolutions=RESOLUTIONS,
        chunk_sizes=CHUNK_SIZES,
        num_runs=NUM_RUNS,
    )
    
    # Save and visualize results
    save_results(results, f'{RESULT_DIR}/dask_vs_numpy_benchmark.csv')
    plot_comparison(results, f'{RESULT_DIR}/dask_vs_numpy_comparison.png')
    
    # Print summary
    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    
    # Find best Dask configuration for each resolution
    for res in RESOLUTIONS:
        numpy_time = next(r[3] for r in results if r[0] == "NumPy" and r[1] == res)
        dask_configs = [(r[2], r[3]) for r in results if r[0] == "Dask" and r[1] == res]
        
        if dask_configs:
            best_chunk, best_time = min(dask_configs, key=lambda x: x[1])
            speedup = numpy_time / best_time
            print(f"{res}x{res}: Best Dask chunk={best_chunk}, "
                  f"speedup={speedup:.2f}x vs NumPy")
