import matplotlib.pyplot as plt
import time
import numpy as np
from numba import jit
import multiprocessing as mp

from config import XMIN, XMAX, YMIN, YMAX, MAX_ITER, RESOLUTION_RAMP_UP, RESULT_DIR, CHUNK_SIZE
from miniproject_1 import numpy_implementation, visualize

def export_to_csv(filename, data):
    if isinstance(data, list) and isinstance(data[0], tuple):
        # Timing results
        import csv
        with open(filename, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Implementation','Resolution','Time (seconds)'])
            writer.writerows(data)
    else:
        # Mandelbrot set array
        np.savetxt(filename, data, delimiter=',', fmt='%d')

# Generated by Claude Opus 4.5 on 2026-04-03
def generate_chunks(xmin, xmax, ymin, ymax, width, height, chunk_w, chunk_h):
    """
    Generate chunk metadata with bounds and pixel positions.
    Returns list of chunk info: (start_col, start_row, chunk_xmin, chunk_xmax, chunk_ymin, chunk_ymax, chunk_width, chunk_height)
    """
    if chunk_h <= 0 or chunk_w <= 0:
        raise ValueError("chunk_h and chunk_w must be > 0")
    
    # Calculate scaling factors
    x_scale = (xmax - xmin) / width
    y_scale = (ymax - ymin) / height
    
    chunks = []
    for r in range(0, height, chunk_h):
        for c in range(0, width, chunk_w):
            # Calculate chunk dimensions
            c_width = min(chunk_w, width - c)
            c_height = min(chunk_h, height - r)
            
            # Calculate proportional bounds for this chunk
            c_xmin = xmin + c * x_scale
            c_xmax = xmin + (c + c_width) * x_scale
            c_ymin = ymin + r * y_scale
            c_ymax = ymin + (r + c_height) * y_scale
            
            chunks.append((c, r, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height))
    
    return chunks


# Generated by Claude Opus 4.5 on 2026-04-03
def process_chunk(chunk_info):
    """
    Process a single chunk using numpy_implementation.
    Returns (start_col, start_row, result_array) for placement in final image.
    """
    start_col, start_row, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height = chunk_info
    result = numpy_implementation(c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height, MAX_ITER)
    return (start_col, start_row, result)


# Generated by Claude Opus 4.5 on 2026-04-03
def compute_mandelbrot_parallel(xmin, xmax, ymin, ymax, width, height, chunk_w, chunk_h, num_processes=None):
    """
    Compute Mandelbrot set using multiprocessing with chunked workload.
    """
    if num_processes is None:
        num_processes = mp.cpu_count()
    
    # Generate all chunks
    chunks = generate_chunks(xmin, xmax, ymin, ymax, width, height, chunk_w, chunk_h)
    
    # Process chunks in parallel
    with mp.Pool(processes=num_processes) as pool:
        results = pool.map(process_chunk, chunks)
    
    # Combine results into final image
    final_image = np.zeros((height, width), dtype=int)
    for start_col, start_row, chunk_result in results:
        for row_idx, row_data in enumerate(chunk_result):
            for col_idx, val in enumerate(row_data):
                final_image[start_row + row_idx, start_col + col_idx] = val
    
    return final_image


if __name__ == "__main__":

    save_csv = input("Do you want to save the results to CSV? (y/n): ").lower() == 'y'

    results = []
    last_result = None  # To store the last computed result for potential visualization

    for res in RESOLUTION_RAMP_UP:
        print(f"\nCalculating Mandelbrot set at resolution {res}x{res}...")
        WIDTH, HEIGHT = res, res
        mp_start = time.perf_counter()
        result = compute_mandelbrot_parallel(XMIN, XMAX, YMIN, YMAX, WIDTH, HEIGHT, CHUNK_SIZE, CHUNK_SIZE)
        mp_end = time.perf_counter()
        last_result = result  # Store last result for potential visualization
        results.append(("Multi-process Numpy", res, mp_end - mp_start))
    
        print(f"Computing Mandelbrot set ({WIDTH}x{HEIGHT}) with {mp.cpu_count()} processes...")
        print(f"Completed in {mp_end - mp_start:.3f} seconds")
        if save_csv:
            export_to_csv(f"{RESULT_DIR}/multi_process_mb_set_{res}x{res}.csv", result)
    
    print("\nResults:")
    for name, resolution, time_taken in results:
        print(60*"=")
        print(f"{name} at {resolution}x{resolution}: {time_taken:.6f} seconds")

    #visualize("Native Implementation", last_result, XMIN, XMAX, YMIN, YMAX)

    if save_csv:
        export_to_csv(f"{RESULT_DIR}/timing_results.csv", results)
        print("Results saved to CSV files.")
    

    
    
    

  
    
 
