# Generated by Claude Sonnet 4.5 on 2026-02-26
"""
Tower of Hanoi Simulation with Reinforcement Learning
Supports both Q-Learning (tabular) and Deep Q-Learning (DQN with GPU acceleration).
"""

import numpy as np
import pickle
import time
import random
import argparse
from collections import defaultdict, deque, namedtuple
from typing import Tuple, List, Optional

# Try to import PyTorch for DQN
try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    PYTORCH_AVAILABLE = True
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
except ImportError:
    PYTORCH_AVAILABLE = False
    device = None
    print("PyTorch not found. DQN will not be available. Install with: pip install torch")


class HanoiTower:
    """Tower of Hanoi environment for reinforcement learning."""
    
    def __init__(self, num_disks: int = 3):
        """
        Initialize the Tower of Hanoi environment.
        
        Args:
            num_disks: Number of disks in the game (default: 3)
        """
        self.num_disks = num_disks
        self.reset()
        
    def reset(self) -> Tuple:
        """Reset the environment to initial state."""
        # State: tuple of three tuples representing the three pegs
        # Disks are numbered 1 (smallest) to num_disks (largest)
        self.state = (
            tuple(range(self.num_disks, 0, -1)),  # Peg A (source) - all disks
            (),  # Peg B (auxiliary)
            ()   # Peg C (destination)
        )
        self.moves = 0
        return self.state
    
    def get_state(self) -> Tuple:
        """Return current state."""
        return self.state
    
    def is_valid_move(self, from_peg: int, to_peg: int) -> bool:
        """
        Check if a move is valid.
        
        Args:
            from_peg: Index of peg to move from (0, 1, or 2)
            to_peg: Index of peg to move to (0, 1, or 2)
            
        Returns:
            True if move is valid, False otherwise
        """
        if from_peg == to_peg:
            return False
        
        if len(self.state[from_peg]) == 0:
            return False  # No disk to move
        
        if len(self.state[to_peg]) == 0:
            return True  # Can always move to empty peg
        
        # Check if top disk of from_peg is smaller than top disk of to_peg
        return self.state[from_peg][-1] < self.state[to_peg][-1]
    
    def step(self, action: int) -> Tuple[Tuple, float, bool, dict]:
        """
        Execute a move.
        
        Args:
            action: Action to take (0-5 representing moves between pegs)
                    0: A->B, 1: A->C, 2: B->A, 3: B->C, 4: C->A, 5: C->B
                    
        Returns:
            Tuple of (new_state, reward, done, info)
        """
        # Map action to from_peg and to_peg
        action_map = [
            (0, 1),  # A->B
            (0, 2),  # A->C
            (1, 0),  # B->A
            (1, 2),  # B->C
            (2, 0),  # C->A
            (2, 1)   # C->B
        ]
        
        from_peg, to_peg = action_map[action]
        
        if not self.is_valid_move(from_peg, to_peg):
            # Invalid move - negative reward
            return self.state, -20, False, {"invalid_move": True}
        
        # Execute the move
        state_list = [list(peg) for peg in self.state]
        disk = state_list[from_peg].pop()
        state_list[to_peg].append(disk)
        self.state = tuple(tuple(peg) for peg in state_list)
        self.moves += 1
        
        # Check if puzzle is solved
        done = len(self.state[2]) == self.num_disks
        
        if done:
            # Positive reward for solving, large bonus for efficiency
            optimal_moves = 2**self.num_disks - 1
            efficiency_bonus = max(0, (optimal_moves - self.moves) * 20)
            reward = 100 + efficiency_bonus
        else:
            # Reward progress towards goal (disks on destination peg)
            progress_reward = len(self.state[2]) * 1.5
            # Strong penalty for inefficiency - encourages minimal moves
            reward = -15 + progress_reward
        
        return self.state, reward, done, {}
    
    def get_valid_actions(self) -> List[int]:
        """Return list of valid actions from current state."""
        valid_actions = []
        for action in range(6):
            action_map = [(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]
            from_peg, to_peg = action_map[action]
            if self.is_valid_move(from_peg, to_peg):
                valid_actions.append(action)
        return valid_actions
    
    def render(self):
        """Print current state in a readable format."""
        print(f"\nMove {self.moves}:")
        print("=" * 40)
        
        # Find max height for display
        max_height = max(len(peg) for peg in self.state)
        
        # Print from top to bottom
        for level in range(max_height - 1, -1, -1):
            line = ""
            for peg_idx in range(3):
                peg = self.state[peg_idx]
                if level < len(peg):
                    disk = peg[level]
                    line += f"  {disk}  "
                else:
                    line += "  |  "
            print(line)
        
        # Print base
        print("-" * 40)
        print("  1     2     3")
        print("=" * 40)


class QLearningAgent:
    """Q-Learning agent for solving Tower of Hanoi."""
    
    def __init__(self, learning_rate: float = 0.1, discount_factor: float = 0.95,
                 epsilon: float = 1.0, epsilon_decay: float = 0.995, epsilon_min: float = 0.01):
        """
        Initialize Q-Learning agent.
        
        Args:
            learning_rate: Learning rate (alpha)
            discount_factor: Discount factor (gamma)
            epsilon: Initial exploration rate
            epsilon_decay: Decay rate for epsilon
            epsilon_min: Minimum epsilon value
        """
        self.q_table = defaultdict(lambda: np.zeros(6))  # 6 possible actions
        self.lr = learning_rate
        self.gamma = discount_factor
        self.epsilon = epsilon
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min
        
    def get_action(self, state: Tuple, valid_actions: List[int], training: bool = True) -> int:
        """
        Choose an action using epsilon-greedy policy.
        
        Args:
            state: Current state
            valid_actions: List of valid actions in current state
            training: Whether in training mode
            
        Returns:
            Selected action
        """
        if not valid_actions:
            return 0  # Default action (shouldn't happen)
        
        # Epsilon-greedy exploration
        if training and np.random.random() < self.epsilon:
            return np.random.choice(valid_actions)
        
        # Exploitation: choose best action among valid ones
        q_values = self.q_table[state]
        valid_q_values = [(action, q_values[action]) for action in valid_actions]
        return max(valid_q_values, key=lambda x: x[1])[0]
    
    def update(self, state: Tuple, action: int, reward: float, next_state: Tuple, 
               next_valid_actions: List[int], done: bool):
        """
        Update Q-table using Q-learning update rule.
        
        Args:
            state: Current state
            action: Action taken
            reward: Reward received
            next_state: Next state
            next_valid_actions: Valid actions in next state
            done: Whether episode is done
        """
        current_q = self.q_table[state][action]
        
        if done:
            target_q = reward
        else:
            # Max Q-value among valid next actions
            next_q_values = self.q_table[next_state]
            if next_valid_actions:
                max_next_q = max(next_q_values[a] for a in next_valid_actions)
            else:
                max_next_q = 0
            target_q = reward + self.gamma * max_next_q
        
        # Q-learning update
        self.q_table[state][action] = current_q + self.lr * (target_q - current_q)
    
    def decay_epsilon(self):
        """Decay exploration rate."""
        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
    
    def save(self, filename: str):
        """Save Q-table to file."""
        with open(filename, 'wb') as f:
            pickle.dump(dict(self.q_table), f)
        print(f"Q-table saved to {filename}")
    
    def load(self, filename: str):
        """Load Q-table from file."""
        with open(filename, 'rb') as f:
            q_dict = pickle.load(f)
            self.q_table = defaultdict(lambda: np.zeros(6), q_dict)
        print(f"Q-table loaded from {filename}")


# ============================================================
# Deep Q-Learning (DQN) - GPU Accelerated
# ============================================================

if PYTORCH_AVAILABLE:
    # Experience replay memory
    Experience = namedtuple('Experience', ['state', 'action', 'reward', 'next_state', 'done'])

    class DQN(nn.Module):
        """Deep Q-Network for Tower of Hanoi."""
        
        def __init__(self, state_size: int, action_size: int, hidden_size: int = 256):
            """Initialize DQN with neural network layers."""
            super(DQN, self).__init__()
            self.network = nn.Sequential(
                nn.Linear(state_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, hidden_size),
                nn.ReLU(),
                nn.Linear(hidden_size, action_size)
            )
            
        def forward(self, x):
            """Forward pass through network."""
            return self.network(x)

    class ReplayBuffer:
        """Experience replay buffer for DQN."""
        
        def __init__(self, capacity: int = 100000):
            """Initialize replay buffer with maximum capacity."""
            self.buffer = deque(maxlen=capacity)
        
        def push(self, experience: Experience):
            """Add experience to buffer."""
            self.buffer.append(experience)
        
        def sample(self, batch_size: int) -> List[Experience]:
            """Sample random batch of experiences."""
            return random.sample(self.buffer, batch_size)
        
        def __len__(self):
            """Return current size of buffer."""
            return len(self.buffer)

    class DQNAgent:
        """DQN Agent with GPU acceleration."""
        
        def __init__(self, state_size: int, action_size: int, 
                     learning_rate: float = 0.001,
                     gamma: float = 0.99,
                     epsilon: float = 1.0,
                     epsilon_decay: float = 0.9995,
                     epsilon_min: float = 0.01,
                     batch_size: int = 128,
                     memory_size: int = 100000):
            """Initialize DQN Agent with neural networks."""
            self.state_size = state_size
            self.action_size = action_size
            self.gamma = gamma
            self.epsilon = epsilon
            self.epsilon_decay = epsilon_decay
            self.epsilon_min = epsilon_min
            self.batch_size = batch_size
            
            # Networks
            self.policy_net = DQN(state_size, action_size).to(device)
            self.target_net = DQN(state_size, action_size).to(device)
            self.target_net.load_state_dict(self.policy_net.state_dict())
            self.target_net.eval()
            
            # Optimizer and loss
            self.optimizer = optim.Adam(self.policy_net.parameters(), lr=learning_rate)
            self.criterion = nn.SmoothL1Loss()
            
            # Replay memory
            self.memory = ReplayBuffer(memory_size)
            
        def state_to_tensor(self, state: Tuple) -> torch.Tensor:
            """Convert state tuple to neural network input tensor."""
            state_array = np.zeros(self.state_size)
            idx = 0
            for peg_idx, peg in enumerate(state):
                for disk in peg:
                    state_array[idx] = peg_idx + 1  # Peg number (1, 2, 3)
                    state_array[idx + 1] = disk  # Disk number
                    idx += 2
            return torch.FloatTensor(state_array).unsqueeze(0).to(device)
        
        def get_action(self, state: Tuple, valid_actions: List[int], training: bool = True) -> int:
            """Select action using epsilon-greedy policy."""
            if not valid_actions:
                return 0
            
            # Exploration
            if training and random.random() < self.epsilon:
                return random.choice(valid_actions)
            
            # Exploitation
            with torch.no_grad():
                state_tensor = self.state_to_tensor(state)
                q_values = self.policy_net(state_tensor).cpu().numpy()[0]
                
                # Mask invalid actions
                masked_q_values = np.full(self.action_size, -np.inf)
                for action in valid_actions:
                    masked_q_values[action] = q_values[action]
                
                return int(np.argmax(masked_q_values))
        
        def remember(self, state: Tuple, action: int, reward: float, 
                     next_state: Tuple, done: bool):
            """Store experience in replay buffer."""
            experience = Experience(state, action, reward, next_state, done)
            self.memory.push(experience)
        
        def train_step(self):
            """Perform one training step using batch from replay buffer."""
            if len(self.memory) < self.batch_size:
                return 0.0
            
            # Sample batch
            experiences = self.memory.sample(self.batch_size)
            
            # Convert to tensors
            states = torch.cat([self.state_to_tensor(e.state) for e in experiences]).to(device)
            actions = torch.LongTensor([e.action for e in experiences]).unsqueeze(1).to(device)
            rewards = torch.FloatTensor([e.reward for e in experiences]).unsqueeze(1).to(device)
            next_states = torch.cat([self.state_to_tensor(e.next_state) for e in experiences]).to(device)
            dones = torch.FloatTensor([e.done for e in experiences]).unsqueeze(1).to(device)
            
            # Current Q values
            current_q_values = self.policy_net(states).gather(1, actions)
            
            # Target Q values
            with torch.no_grad():
                next_q_values = self.target_net(next_states).max(1)[0].unsqueeze(1)
                target_q_values = rewards + (1 - dones) * self.gamma * next_q_values
            
            # Compute loss
            loss = self.criterion(current_q_values, target_q_values)
            
            # Optimize
            self.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.policy_net.parameters(), 1.0)
            self.optimizer.step()
            
            return loss.item()
        
        def update_target_network(self):
            """Copy weights from policy network to target network."""
            self.target_net.load_state_dict(self.policy_net.state_dict())
        
        def decay_epsilon(self):
            """Decay exploration rate."""
            self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
        
        def save(self, filename: str):
            """Save model to file."""
            torch.save({
                'policy_net': self.policy_net.state_dict(),
                'target_net': self.target_net.state_dict(),
                'optimizer': self.optimizer.state_dict(),
                'epsilon': self.epsilon
            }, filename)
            print(f"Model saved to {filename}")
        
        def load(self, filename: str):
            """Load model from file."""
            checkpoint = torch.load(filename, map_location=device)
            self.policy_net.load_state_dict(checkpoint['policy_net'])
            self.target_net.load_state_dict(checkpoint['target_net'])
            self.optimizer.load_state_dict(checkpoint['optimizer'])
            self.epsilon = checkpoint['epsilon']
            print(f"Model loaded from {filename}")


# ============================================================
# Training Functions
# ============================================================


def train_agent(num_disks: int = 3, episodes: int = 5000, verbose: bool = True,
                learning_rate: float = 0.1, discount_factor: float = 0.95,
                epsilon_decay: float = 0.9995) -> QLearningAgent:
    """
    Train Q-learning agent to solve Tower of Hanoi.
    
    Args:
        num_disks: Number of disks
        episodes: Number of training episodes
        verbose: Whether to print progress
        learning_rate: Learning rate for Q-learning
        discount_factor: Discount factor for future rewards
        epsilon_decay: Decay rate for exploration
        
    Returns:
        Trained agent
    """
    env = HanoiTower(num_disks)
    agent = QLearningAgent(learning_rate=learning_rate, 
                          discount_factor=discount_factor,
                          epsilon_decay=epsilon_decay)
    
    rewards_history = []
    moves_history = []
    success_rate = []
    
    start_time = time.time()
    
    for episode in range(episodes):
        state = env.reset()
        total_reward = 0
        done = False
        max_steps = 1000  # Allow more steps for complex problems
        steps = 0
        
        while not done and steps < max_steps:
            valid_actions = env.get_valid_actions()
            action = agent.get_action(state, valid_actions)
            next_state, reward, done, _ = env.step(action)
            next_valid_actions = env.get_valid_actions()
            
            agent.update(state, action, reward, next_state, next_valid_actions, done)
            
            state = next_state
            total_reward += reward
            steps += 1
        
        agent.decay_epsilon()
        rewards_history.append(total_reward)
        moves_history.append(env.moves)
        
        # Calculate success rate over last 100 episodes
        if episode >= 99:
            recent_success = sum(1 for i in range(episode-99, episode+1) 
                               if rewards_history[i] > 0)
            success_rate.append(recent_success / 100)
        
        # Print progress
        if verbose and (episode + 1) % 500 == 0:
            elapsed = time.time() - start_time
            avg_reward = np.mean(rewards_history[-500:])
            avg_moves = np.mean(moves_history[-500:])
            current_success = success_rate[-1] if success_rate else 0
            print(f"Episode {episode + 1}/{episodes} | Time: {elapsed:.1f}s")
            print(f"  Avg Reward: {avg_reward:.2f}")
            print(f"  Avg Moves: {avg_moves:.2f}")
            print(f"  Success Rate: {current_success:.2%}")
            print(f"  Epsilon: {agent.epsilon:.4f}")
    
    training_time = time.time() - start_time
    
    if verbose:
        optimal_moves = 2**num_disks - 1
        print(f"\nTraining completed in {training_time:.2f} seconds ({training_time/60:.2f} minutes)")
        print(f"Optimal solution requires {optimal_moves} moves")
    
    return agent


def train_dqn_agent(num_disks: int = 5, episodes: int = 10000, 
                    target_update: int = 100, verbose: bool = True):
    """
    Train DQN agent on Tower of Hanoi with GPU acceleration.
    
    Args:
        num_disks: Number of disks
        episodes: Number of training episodes
        target_update: Episodes between target network updates
        verbose: Whether to print progress
        
    Returns:
        Trained DQN agent
    """
    if not PYTORCH_AVAILABLE:
        raise ImportError("PyTorch is required for DQN. Install with: pip install torch")
    
    env = HanoiTower(num_disks)
    
    # State size: 2 values per disk (peg number, disk number)
    state_size = num_disks * 2
    action_size = 6
    
    agent = DQNAgent(state_size, action_size, 
                    learning_rate=0.001,
                    gamma=0.99,
                    epsilon=1.0,
                    epsilon_decay=0.9995,
                    batch_size=128)
    
    rewards_history = []
    moves_history = []
    loss_history = []
    success_rate = []
    
    start_time = time.time()
    
    for episode in range(episodes):
        state = env.reset()
        total_reward = 0
        done = False
        max_steps = 1000
        steps = 0
        episode_loss = []
        
        while not done and steps < max_steps:
            valid_actions = env.get_valid_actions()
            action = agent.get_action(state, valid_actions)
            next_state, reward, done, _ = env.step(action)
            
            # Store experience
            agent.remember(state, action, reward, next_state, done)
            
            # Train on batch (GPU parallel processing)
            loss = agent.train_step()
            if loss > 0:
                episode_loss.append(loss)
            
            state = next_state
            total_reward += reward
            steps += 1
        
        agent.decay_epsilon()
        rewards_history.append(total_reward)
        moves_history.append(env.moves)
        if episode_loss:
            loss_history.append(np.mean(episode_loss))
        
        # Update target network
        if (episode + 1) % target_update == 0:
            agent.update_target_network()
        
        # Calculate success rate
        if episode >= 99:
            recent_success = sum(1 for i in range(episode-99, episode+1) 
                               if rewards_history[i] > 0)
            success_rate.append(recent_success / 100)
        
        # Print progress
        if verbose and (episode + 1) % 1000 == 0:
            elapsed = time.time() - start_time
            avg_reward = np.mean(rewards_history[-1000:])
            avg_moves = np.mean(moves_history[-1000:])
            avg_loss = np.mean(loss_history[-1000:]) if loss_history else 0
            current_success = success_rate[-1] if success_rate else 0
            print(f"Episode {episode + 1}/{episodes} | Time: {elapsed:.1f}s | Device: {device}")
            print(f"  Avg Reward: {avg_reward:.2f}")
            print(f"  Avg Moves: {avg_moves:.2f}")
            print(f"  Avg Loss: {avg_loss:.4f}")
            print(f"  Success Rate: {current_success:.2%}")
            print(f"  Epsilon: {agent.epsilon:.4f}")
            print(f"  Memory Size: {len(agent.memory)}")
    
    training_time = time.time() - start_time
    
    if verbose:
        optimal_moves = 2**num_disks - 1
        print(f"\nTraining completed in {training_time:.2f} seconds ({training_time/60:.2f} minutes)")
        print(f"Optimal solution requires {optimal_moves} moves")
    
    return agent


def test_agent(agent: QLearningAgent, num_disks: int = 3, render: bool = True):
    """
    Test trained agent on Tower of Hanoi.
    
    Args:
        agent: Trained agent
        num_disks: Number of disks
        render: Whether to render the initial and final state
    """
    env = HanoiTower(num_disks)
    state = env.reset()
    
    if render:
        print("\n" + "="*40)
        print(f"Testing Agent on {num_disks}-disk Tower of Hanoi")
        print("="*40)
        env.render()
    
    done = False
    optimal_moves = 2**num_disks - 1
    max_steps = optimal_moves * 5  # Allow 5x optimal moves for poorly trained agents
    steps = 0
    
    while not done and steps < max_steps:
        valid_actions = env.get_valid_actions()
        action = agent.get_action(state, valid_actions, training=False)
        state, reward, done, _ = env.step(action)
        steps += 1
    
    if render:
        print("\n" + "="*40)
        print("Final state:")
        print("="*40)
        env.render()
    
    optimal_moves = 2**num_disks - 1
    print(f"\n{'='*40}")
    print(f"Solution found in {env.moves} moves")
    print(f"Optimal solution: {optimal_moves} moves")
    print(f"Efficiency: {optimal_moves/env.moves*100:.1f}%")
    print(f"{'='*40}\n")


def test_dqn_agent(agent, num_disks: int = 5, render: bool = True):
    """
    Test trained DQN agent.
    
    Args:
        agent: Trained DQN agent
        num_disks: Number of disks
        render: Whether to render states
    """
    env = HanoiTower(num_disks)
    state = env.reset()
    
    if render:
        print("\n" + "="*40)
        print(f"Testing DQN Agent on {num_disks}-disk Tower of Hanoi")
        print("="*40)
        env.render()
    
    done = False
    optimal_moves = 2**num_disks - 1
    max_steps = optimal_moves * 3
    steps = 0
    
    while not done and steps < max_steps:
        valid_actions = env.get_valid_actions()
        action = agent.get_action(state, valid_actions, training=False)
        state, reward, done, _ = env.step(action)
        steps += 1
    
    if render:
        print("\n" + "="*40)
        print("Final state:")
        print("="*40)
        env.render()
    
    optimal_moves = 2**num_disks - 1
    print(f"\n{'='*40}")
    print(f"Solution found in {env.moves} moves")
    print(f"Optimal solution: {optimal_moves} moves")
    print(f"Efficiency: {optimal_moves/env.moves*100:.1f}%")
    print(f"{'='*40}\n")


def main():
    """Main function to demonstrate Tower of Hanoi RL solutions."""
    # Parse command-line arguments
    parser = argparse.ArgumentParser(description='Train Tower of Hanoi RL agent')
    parser.add_argument('--algorithm', '-a', type=str, choices=['qlearning', 'dqn'], 
                       default='qlearning', help='Algorithm to use (default: qlearning)')
    parser.add_argument('--disks', '-d', type=int, default=5, 
                       help='Number of disks (default: 5)')
    parser.add_argument('--episodes', '-e', type=int, default=None,
                       help='Training episodes (default: 10000 for qlearning, 20000 for dqn)')
    parser.add_argument('--interactive', '-i', action='store_true',
                       help='Use interactive mode with prompts')
    args = parser.parse_args()
    
    print("Tower of Hanoi - Reinforcement Learning Solver")
    print("="*60)
    
    # Interactive mode (original behavior)
    if args.interactive:
        print("\nAvailable algorithms:")
        print("  1. Q-Learning (tabular, CPU only)")
        if PYTORCH_AVAILABLE:
            print(f"  2. Deep Q-Learning (DQN, GPU: {device})")
        else:
            print("  2. Deep Q-Learning (DQN) - NOT AVAILABLE (install torch)")
        
        choice = input("\nSelect algorithm (1 or 2, default=1): ").strip() or "1"
        NUM_DISKS = int(input("Number of disks (3-8, default=5): ").strip() or "5")
        
        if choice == "1":
            args.algorithm = 'qlearning'
        elif choice == "2":
            args.algorithm = 'dqn'
        else:
            print("Invalid choice!")
            return
        args.disks = NUM_DISKS
    
    # Set defaults for episodes if not specified
    if args.episodes is None:
        args.episodes = 10000 if args.algorithm == 'qlearning' else 20000
    
    NUM_DISKS = args.disks
    EPISODES = args.episodes
    
    if args.algorithm == 'qlearning':
        # Q-Learning
        print("\n" + "="*60)
        print("Using Q-Learning (Tabular)")
        print("="*60)
        print(f"Configuration: {NUM_DISKS} disks, {EPISODES} episodes")
        print("-"*60)
        
        # Train the agent
        agent = train_agent(num_disks=NUM_DISKS, 
                           episodes=EPISODES, 
                           verbose=True,
                           learning_rate=0.2,
                           discount_factor=0.99,
                           epsilon_decay=0.9998)
        
        # Save the trained agent
        agent.save(f"hanoi_qlearn_{NUM_DISKS}disks.pkl")
        
        # Test the agent
        print("\n" + "="*60)
        print("Testing trained Q-Learning agent...")
        print("="*60)
        test_agent(agent, num_disks=NUM_DISKS, render=True)
        
    elif args.algorithm == 'dqn':
        if not PYTORCH_AVAILABLE:
            print("\n❌ PyTorch not available! Install with: pip install torch")
            return
        
        # DQN
        print("\n" + "="*60)
        print(f"Using Deep Q-Learning (DQN) on {device}")
        print("="*60)
        print(f"Configuration: {NUM_DISKS} disks, {EPISODES} episodes")
        print("-"*60)
        
        # Train the agent
        agent = train_dqn_agent(num_disks=NUM_DISKS, 
                               episodes=EPISODES, 
                               target_update=100,
                               verbose=True)
        
        # Save the trained agent
        agent.save(f"hanoi_dqn_{NUM_DISKS}disks.pth")
        
        # Test the agent
        print("\n" + "="*60)
        print("Testing trained DQN agent...")
        print("="*60)
        test_dqn_agent(agent, num_disks=NUM_DISKS, render=True)


if __name__ == "__main__":
    main()
