# Generated by Claude Sonnet 4.5 on 2026-02-26
"""
Interactive Tower of Hanoi Game
Play the Tower of Hanoi game in the terminal.
"""

import sys
from main import HanoiTower


def print_instructions():
    """Print game instructions."""
    print("\n" + "="*60)
    print("TOWER OF HANOI - Interactive Game")
    print("="*60)
    print("\nGOAL: Move all disks from peg 1 to peg 3")
    print("\nRULES:")
    print("  1. Only one disk can be moved at a time")
    print("  2. A larger disk cannot be placed on a smaller disk")
    print("  3. Only the top disk of a peg can be moved")
    print("\nCONTROLS:")
    print("  Enter moves as two digits (e.g., '13' to move from peg 1 to peg 3)")
    print("  Pegs: 1 (left), 2 (middle), 3 (right)")
    print("  Type 'quit' or 'q' to exit")
    print("  Type 'reset' or 'r' to restart")
    print("  Type 'help' or 'h' for instructions")
    print("="*60 + "\n")


def get_optimal_moves(num_disks: int) -> int:
    """Calculate optimal number of moves."""
    return 2**num_disks - 1


def play_game(num_disks: int = 3):
    """
    Play the Tower of Hanoi game interactively.
    
    Args:
        num_disks: Number of disks to play with
    """
    env = HanoiTower(num_disks)
    optimal = get_optimal_moves(num_disks)
    
    print(f"\nStarting game with {num_disks} disks")
    print(f"Optimal solution: {optimal} moves")
    print(f"Current moves: {env.moves}")
    env.render()
    
    # Map peg numbers to indices
    peg_map = {'1': 0, '2': 1, '3': 2}
    action_map = {
        (0, 1): 0,  # 1->2
        (0, 2): 1,  # 1->3
        (1, 0): 2,  # 2->1
        (1, 2): 3,  # 2->3
        (2, 0): 4,  # 3->1
        (2, 1): 5   # 3->2
    }
    
    while True:
        # Get user input
        try:
            user_input = input("\nEnter move (e.g., 13): ").strip().upper()
            
            # Handle special commands
            if user_input in ['QUIT', 'Q', 'EXIT']:
                print("Thanks for playing!")
                return False
            
            if user_input in ['RESET', 'R', 'RESTART']:
                print("\n" + "="*60)
                print("Restarting game...")
                return True
            
            if user_input in ['HELP', 'H', '?']:
                print_instructions()
                env.render()
                continue
            
            # Parse move (expecting two digits like "13")
            if len(user_input) != 2:
                print("❌ Invalid input! Please enter two digits (e.g., '13' to move from peg 1 to peg 3)")
                continue
            
            from_peg, to_peg = user_input[0], user_input[1]
            
            # Validate peg numbers
            if from_peg not in peg_map or to_peg not in peg_map:
                print("❌ Invalid peg numbers! Use 1, 2, or 3")
                continue
            
            # Convert to action
            from_idx = peg_map[from_peg]
            to_idx = peg_map[to_peg]
            
            if (from_idx, to_idx) not in action_map:
                print("❌ Invalid move combination!")
                continue
            
            action = action_map[(from_idx, to_idx)]
            
            # Execute move
            state, reward, done, info = env.step(action)
            
            if info.get('invalid_move'):
                print("❌ Invalid move! Check the rules:")
                print("   - You can't move from an empty peg")
                print("   - You can't place a larger disk on a smaller one")
                continue
            
            # Display result
            print(f"\n✓ Moved disk from peg {from_peg} to peg {to_peg}")
            print(f"Current moves: {env.moves} (Optimal: {optimal})")
            env.render()
            
            # Check if won
            if done:
                print("\n" + "🎉"*30)
                print("CONGRATULATIONS! You solved the puzzle!")
                print("🎉"*30)
                print(f"\nYour score:")
                print(f"  Moves used: {env.moves}")
                print(f"  Optimal moves: {optimal}")
                if env.moves == optimal:
                    print(f"  Performance: PERFECT! ⭐⭐⭐")
                elif env.moves <= optimal * 1.5:
                    print(f"  Performance: Great! ⭐⭐")
                elif env.moves <= optimal * 2:
                    print(f"  Performance: Good! ⭐")
                else:
                    print(f"  Performance: Keep practicing!")
                print(f"  Efficiency: {optimal/env.moves*100:.1f}%")
                print()
                
                # Ask if they want to play again
                play_again = input("Play again? (y/n): ").strip().lower()
                if play_again in ['y', 'yes']:
                    return True
                else:
                    print("Thanks for playing!")
                    return False
                
        except KeyboardInterrupt:
            print("\n\nGame interrupted. Thanks for playing!")
            return False
        except Exception as e:
            print(f"❌ Error: {e}")
            continue


def main():
    """Main function to run the interactive game."""
    print_instructions()
    
    # Get number of disks
    while True:
        try:
            num_disks = input("Enter number of disks (3-8 recommended): ").strip()
            
            if num_disks.lower() in ['quit', 'q', 'exit']:
                print("Goodbye!")
                return
            
            num_disks = int(num_disks)
            
            if num_disks < 1:
                print("❌ Please enter at least 1 disk")
                continue
            elif num_disks > 10:
                confirm = input(f"⚠️  {num_disks} disks will be very challenging! Continue? (y/n): ")
                if confirm.lower() not in ['y', 'yes']:
                    continue
            
            break
            
        except ValueError:
            print("❌ Please enter a valid number")
        except KeyboardInterrupt:
            print("\nGoodbye!")
            return
    
    # Play game loop
    while True:
        play_again = play_game(num_disks)
        if not play_again:
            break


if __name__ == "__main__":
    main()
