# Generated by Claude Sonnet 4.5 on 2026-02-26
"""
Tower of Hanoi - Solution Demo
Load a trained agent and watch it solve the puzzle.
"""

import sys
import os
import time
from main import HanoiTower, QLearningAgent

# Try to import PyTorch for DQN
try:
    import torch
    from main import DQNAgent, device
    PYTORCH_AVAILABLE = True
except ImportError:
    PYTORCH_AVAILABLE = False


def solve_with_qlearning(filename: str, num_disks: int, show_moves: bool = False):
    """
    Load Q-Learning agent and solve the puzzle.
    
    Args:
        filename: Path to saved Q-Learning agent
        num_disks: Number of disks
        show_moves: Whether to show each move
    """
    print("\n" + "="*60)
    print("Loading Q-Learning Agent...")
    print("="*60)
    
    # Load agent
    agent = QLearningAgent()
    agent.load(filename)
    
    # Create environment
    env = HanoiTower(num_disks)
    state = env.reset()
    
    print(f"\nSolving {num_disks}-disk Tower of Hanoi...")
    print("="*60)
    
    # Show initial state
    env.render()
    
    if show_moves:
        input("\nPress Enter to start solving...")
    
    # Solve
    done = False
    optimal_moves = 2**num_disks - 1
    max_steps = optimal_moves * 3
    steps = 0
    
    while not done and steps < max_steps:
        valid_actions = env.get_valid_actions()
        action = agent.get_action(state, valid_actions, training=False)
        state, reward, done, _ = env.step(action)
        steps += 1
        
        if show_moves:
            env.render()
            if not done:
                time.sleep(0.5)  # Pause between moves
    
    if not show_moves:
        print("\n" + "="*60)
        print("Final state:")
        print("="*60)
        env.render()
    
    # Results
    print(f"\n{'='*60}")
    if done:
        print(f"✅ Puzzle solved in {env.moves} moves!")
        print(f"   Optimal solution: {optimal_moves} moves")
        print(f"   Efficiency: {optimal_moves/env.moves*100:.1f}%")
        if env.moves == optimal_moves:
            print(f"   ⭐⭐⭐ PERFECT SOLUTION! ⭐⭐⭐")
        elif env.moves <= optimal_moves * 1.5:
            print(f"   ⭐⭐ Great solution!")
        else:
            print(f"   ⭐ Good solution!")
    else:
        print(f"❌ Failed to solve within {max_steps} moves")
    print(f"{'='*60}\n")


def solve_with_dqn(filename: str, num_disks: int, show_moves: bool = False):
    """
    Load DQN agent and solve the puzzle.
    
    Args:
        filename: Path to saved DQN agent
        num_disks: Number of disks
        show_moves: Whether to show each move
    """
    if not PYTORCH_AVAILABLE:
        print("❌ PyTorch not available! Cannot load DQN agent.")
        print("   Install with: pip install torch")
        return
    
    print("\n" + "="*60)
    print(f"Loading DQN Agent... (Device: {device})")
    print("="*60)
    
    # Create agent
    state_size = num_disks * 2
    action_size = 6
    agent = DQNAgent(state_size, action_size)
    agent.load(filename)
    
    # Create environment
    env = HanoiTower(num_disks)
    state = env.reset()
    
    print(f"\nSolving {num_disks}-disk Tower of Hanoi with DQN...")
    print("="*60)
    
    # Show initial state
    env.render()
    
    if show_moves:
        input("\nPress Enter to start solving...")
    
    # Solve
    done = False
    optimal_moves = 2**num_disks - 1
    max_steps = optimal_moves * 3
    steps = 0
    
    while not done and steps < max_steps:
        valid_actions = env.get_valid_actions()
        action = agent.get_action(state, valid_actions, training=False)
        state, reward, done, _ = env.step(action)
        steps += 1
        
        if show_moves:
            env.render()
            if not done:
                time.sleep(0.5)  # Pause between moves
    
    if not show_moves:
        print("\n" + "="*60)
        print("Final state:")
        print("="*60)
        env.render()
    
    # Results
    print(f"\n{'='*60}")
    if done:
        print(f"✅ Puzzle solved in {env.moves} moves!")
        print(f"   Optimal solution: {optimal_moves} moves")
        print(f"   Efficiency: {optimal_moves/env.moves*100:.1f}%")
        if env.moves == optimal_moves:
            print(f"   ⭐⭐⭐ PERFECT SOLUTION! ⭐⭐⭐")
        elif env.moves <= optimal_moves * 1.5:
            print(f"   ⭐⭐ Great solution!")
        else:
            print(f"   ⭐ Good solution!")
    else:
        print(f"❌ Failed to solve within {max_steps} moves")
    print(f"{'='*60}\n")


def list_saved_agents():
    """List all saved agent files in current directory."""
    import glob
    
    qlearn_files = glob.glob("hanoi_qlearn_*.pkl")
    dqn_files = glob.glob("hanoi_dqn_*.pth")
    legacy_files = glob.glob("hanoi_agent_*.pkl")
    
    print("\nAvailable trained agents:")
    print("-" * 60)
    
    if qlearn_files or legacy_files:
        print("\nQ-Learning agents (.pkl):")
        for f in qlearn_files + legacy_files:
            print(f"  - {f}")
    
    if dqn_files:
        print("\nDQN agents (.pth):")
        for f in dqn_files:
            print(f"  - {f}")
    
    if not (qlearn_files or dqn_files or legacy_files):
        print("  No saved agents found.")
        print("  Train an agent first using main.py")
    
    print("-" * 60)


def main():
    """Main function to demonstrate trained agent solutions."""
    print("Tower of Hanoi - Solution Demo")
    print("="*60)
    print("Watch a trained agent solve the puzzle!")
    print("="*60)
    
    # List available agents
    list_saved_agents()
    
    # Choose agent type
    print("\nAgent types:")
    print("  1. Q-Learning (.pkl file)")
    if PYTORCH_AVAILABLE:
        print("  2. DQN (.pth file)")
    else:
        print("  2. DQN - NOT AVAILABLE (install torch)")
    
    choice = input("\nSelect agent type (1 or 2): ").strip()
    
    # Get filename and disk count
    filename = input("Enter agent filename (or press Enter for default): ").strip()
    num_disks = int(input("Number of disks (default=5): ").strip() or "5")
    
    show_moves = input("Show each move? (y/n, default=n): ").strip().lower() == 'y'
    
    # Solve based on choice
    if choice == "1":
        if not filename:
            filename = f"hanoi_qlearn_{num_disks}disks.pkl"
            if not os.path.exists(filename):
                filename = f"hanoi_agent_{num_disks}disks.pkl"  # Try legacy name
        
        if not os.path.exists(filename):
            print(f"\n❌ File not found: {filename}")
            print("   Train an agent first using main.py")
            return
        
        solve_with_qlearning(filename, num_disks, show_moves)
        
    elif choice == "2":
        if not PYTORCH_AVAILABLE:
            print("\n❌ PyTorch not available! Install with: pip install torch")
            return
        
        if not filename:
            filename = f"hanoi_dqn_{num_disks}disks.pth"
        
        if not os.path.exists(filename):
            print(f"\n❌ File not found: {filename}")
            print("   Train a DQN agent first using main.py")
            return
        
        solve_with_dqn(filename, num_disks, show_moves)
    
    else:
        print("Invalid choice!")


if __name__ == "__main__":
    main()
