#!/bin/bash
# Generated by Claude Sonnet 4.5 on 2026-02-26
# SLURM batch script for Tower of Hanoi training on HPC cluster

#SBATCH --job-name=hanoi_8disks
#SBATCH --output=hanoi_training_%j.log
#SBATCH --error=hanoi_training_%j.err
#SBATCH --time=24:00:00              # Max 24 hours
#SBATCH --ntasks=1                   # Single task
#SBATCH --cpus-per-task=4            # 4 CPU cores
#SBATCH --mem=16G                    # 16GB RAM
#SBATCH --partition=gpu              # GPU partition (adjust for your cluster)
#SBATCH --gres=gpu:1                 # Request 1 GPU (optional, for DQN)

# Load required modules (adjust for your HPC system)
# module load python/3.9
# module load cuda/11.8  # If using DQN with GPU

# Activate virtual environment
source $HOME/venv/bin/activate  # Adjust path to your venv

# Print environment info
echo "=========================================="
echo "Job started at: $(date)"
echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURM_NODELIST"
echo "=========================================="

# Check for GPU (if using DQN)
if command -v nvidia-smi &> /dev/null; then
    echo "GPU Info:"
    nvidia-smi
    echo "=========================================="
fi

# Run training
cd $SLURM_SUBMIT_DIR

# Option 1: Q-Learning (CPU only, reliable)
python3 train_hpc.py --disks 8 --episodes 100000 --algorithm qlearning

# Option 2: DQN (GPU accelerated, requires PyTorch with CUDA)
# python3 train_hpc.py --disks 8 --episodes 50000 --algorithm dqn

echo "=========================================="
echo "Job finished at: $(date)"
echo "=========================================="
