# Generated by Claude Sonnet 4.5 on 2026-02-26
"""
Quick test script for 4-disk Tower of Hanoi with Q-Learning
Run this locally to verify everything works before HPC training.
"""

import sys
sys.path.insert(0, '.')

from main import HanoiTower, QLearningAgent, train_agent, test_agent

def main():
    """Test training with 4 disks."""
    print("Tower of Hanoi - Quick Test (4 disks)")
    print("="*60)
    print("This will train a Q-Learning agent on 4 disks locally")
    print("Expected: ~15 moves optimal solution")
    print("="*60)
    
    NUM_DISKS = 4
    EPISODES = 10000  # Quick test
    
    print(f"\nTraining Q-Learning agent with {NUM_DISKS} disks for {EPISODES} episodes...")
    print("-"*60)
    
    # Train agent
    agent = train_agent(
        num_disks=NUM_DISKS,
        episodes=EPISODES,
        verbose=True,
        learning_rate=0.2,
        discount_factor=0.99,
        epsilon_decay=0.9998
    )
    
    # Save agent
    agent.save(f"hanoi_qlearn_{NUM_DISKS}disks.pkl")
    
    # Test agent
    print("\n" + "="*60)
    print("Testing trained agent...")
    print("="*60)
    test_agent(agent, num_disks=NUM_DISKS, render=True)
    
    print("\n✅ Local test complete!")
    print("   If this works well, you can train the 8-disk version on your HPC cluster.")
    print("   For HPC: Use main.py with choice=1, NUM_DISKS=8, EPISODES=50000+")

if __name__ == "__main__":
    main()
