# Generated by Claude Sonnet 4.5 on 2026-02-26
"""
HPC Training Script for Tower of Hanoi (8 disks)
This script is designed to run on HPC clusters with GPU support.
"""

import sys
import argparse
from main import train_agent, test_agent

def main():
    """Train agent on HPC cluster."""
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Train Tower of Hanoi agent on HPC')
    parser.add_argument('--disks', type=int, default=8, help='Number of disks (default: 8)')
    parser.add_argument('--episodes', type=int, default=100000, help='Training episodes (default: 100000)')
    parser.add_argument('--algorithm', type=str, choices=['qlearning', 'dqn'], default='qlearning',
                       help='Algorithm to use (default: qlearning)')
    parser.add_argument('--output', type=str, default=None, help='Output filename (auto-generated if not provided)')
    args = parser.parse_args()
    
    print("="*80)
    print("Tower of Hanoi HPC Training")
    print("="*80)
    print(f"Configuration:")
    print(f"  Disks: {args.disks}")
    print(f"  Episodes: {args.episodes}")
    print(f"  Algorithm: {args.algorithm.upper()}")
    print("="*80)
    
    if args.algorithm == 'qlearning':
        # Q-Learning training
        print(f"\nTraining Q-Learning agent...")
        print("-"*80)
        
        agent = train_agent(
            num_disks=args.disks,
            episodes=args.episodes,
            verbose=True,
            learning_rate=0.2,
            discount_factor=0.99,
            epsilon_decay=0.9998
        )
        
        # Save agent
        output_file = args.output or f"hanoi_qlearn_{args.disks}disks_hpc.pkl"
        agent.save(output_file)
        
        # Test agent
        print("\n" + "="*80)
        print("Testing trained agent...")
        print("="*80)
        test_agent(agent, num_disks=args.disks, render=False)
        
    elif args.algorithm == 'dqn':
        # Check if PyTorch is available
        try:
            from main import train_dqn_agent, test_dqn_agent, PYTORCH_AVAILABLE
            
            if not PYTORCH_AVAILABLE:
                print("ERROR: PyTorch not available!")
                print("Install with: pip install torch")
                sys.exit(1)
            
            print(f"\nTraining DQN agent with GPU acceleration...")
            print("-"*80)
            
            agent = train_dqn_agent(
                num_disks=args.disks,
                episodes=args.episodes,
                target_update=100,
                verbose=True
            )
            
            # Save agent
            output_file = args.output or f"hanoi_dqn_{args.disks}disks_hpc.pth"
            agent.save(output_file)
            
            # Test agent
            print("\n" + "="*80)
            print("Testing trained DQN agent...")
            print("="*80)
            test_dqn_agent(agent, num_disks=args.disks, render=False)
            
        except ImportError as e:
            print(f"ERROR: {e}")
            print("Make sure PyTorch is installed: pip install torch")
            sys.exit(1)
    
    print("\n" + "="*80)
    print("✅ HPC Training Complete!")
    print("="*80)

if __name__ == "__main__":
    main()
