# Generated by Claude Opus 4 on 2026-05-05
import numpy as np
import pytest

from src import MandelbrotConfig
from src.mb_multiprocess_calculator import _generate_chunks, _process_chunk
from src.mb_numba_calculator import _numba_compute


# ─── Tests for _generate_chunks ─────────────────────────────────────────────


class TestGenerateChunks:
    """Unit tests for the chunk generation helper."""

    def test_single_chunk_covers_whole_image(self):
        cfg = MandelbrotConfig(width=64, height=64, chunk_size=64)
        chunks = _generate_chunks(cfg)
        assert len(chunks) == 1
        col, row, _, _, _, _, c_w, c_h = chunks[0]
        assert col == 0 and row == 0
        assert c_w == 64 and c_h == 64

    def test_chunk_count_2x2(self):
        cfg = MandelbrotConfig(width=128, height=128, chunk_size=64)
        chunks = _generate_chunks(cfg)
        assert len(chunks) == 4

    def test_chunks_cover_full_image(self):
        cfg = MandelbrotConfig(width=100, height=100, chunk_size=32)
        chunks = _generate_chunks(cfg)

        covered = np.zeros((100, 100), dtype=bool)
        for col, row, _, _, _, _, c_w, c_h in chunks:
            covered[row:row + c_h, col:col + c_w] = True
        assert covered.all()

    def test_non_divisible_resolution(self):
        cfg = MandelbrotConfig(width=70, height=50, chunk_size=32)
        chunks = _generate_chunks(cfg)

        total_pixels = sum(c_w * c_h for _, _, _, _, _, _, c_w, c_h in chunks)
        assert total_pixels == 70 * 50

    def test_first_chunk_starts_at_config_bounds(self):
        cfg = MandelbrotConfig(xmin=-2.0, xmax=1.0, ymin=-1.5, ymax=1.5, width=128, height=128, chunk_size=64)
        chunks = _generate_chunks(cfg)
        _, _, c_xmin, _, c_ymin, _, _, _ = chunks[0]
        assert c_xmin == pytest.approx(-2.0)
        assert c_ymin == pytest.approx(-1.5)

    def test_last_chunk_ends_at_config_bounds(self):
        cfg = MandelbrotConfig(xmin=-2.0, xmax=1.0, ymin=-1.5, ymax=1.5, width=128, height=128, chunk_size=64)
        chunks = _generate_chunks(cfg)
        _, _, _, c_xmax, _, c_ymax, _, _ = chunks[-1]
        assert c_xmax == pytest.approx(1.0)
        assert c_ymax == pytest.approx(1.5)


# ─── Tests for _process_chunk ────────────────────────────────────────────────


class TestProcessChunk:
    """Unit tests for the worker function that computes a single chunk."""

    def test_returns_correct_shape(self):
        # chunk args: (start_col, start_row, xmin, xmax, ymin, ymax, width, height, max_iter)
        args = (0, 0, -2.0, 1.0, -1.5, 1.5, 16, 16, 50)
        start_col, start_row, result = _process_chunk(args)
        assert result.shape == (16, 16)
        assert start_col == 0
        assert start_row == 0

    def test_returns_integer_array(self):
        args = (0, 0, -2.0, 1.0, -1.5, 1.5, 8, 8, 20)
        _, _, result = _process_chunk(args)
        assert np.issubdtype(result.dtype, np.integer)

    def test_preserves_start_offsets(self):
        args = (32, 64, -1.0, 0.0, 0.0, 1.0, 16, 16, 30)
        start_col, start_row, _ = _process_chunk(args)
        assert start_col == 32
        assert start_row == 64


# ─── Tests for _numba_compute ────────────────────────────────────────────────


class TestNumbaCompute:
    """Unit tests for the Numba JIT kernel function."""

    def test_output_shape(self):
        result = _numba_compute(-2.0, 1.0, -1.5, 1.5, 32, 32, 50)
        assert result.shape == (32, 32)

    def test_origin_in_set(self):
        """c=0 is in the Mandelbrot set, should hit max_iter."""
        result = _numba_compute(0.0, 0.0, 0.0, 0.0, 1, 1, 100)
        assert result[0, 0] == 100

    def test_far_point_escapes(self):
        """c=10+10j escapes immediately."""
        result = _numba_compute(10.0, 10.0, 10.0, 10.0, 1, 1, 100)
        assert result[0, 0] == 1

    def test_matches_native_calculation(self):
        """Numba kernel should produce same result as NativeCalculator."""
        from src.mb_native_calculator import NativeCalculator

        cfg = MandelbrotConfig(width=16, height=16, max_iter=30)
        native_result = NativeCalculator(cfg).calculate()
        numba_result = _numba_compute(cfg.xmin, cfg.xmax, cfg.ymin, cfg.ymax, cfg.width, cfg.height, cfg.max_iter)
        np.testing.assert_array_equal(native_result, numba_result)

