# Generated by Claude Opus 4 on 2026-05-07
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "benchmark_app"))

from benchmark_app.device_scanner import scan_devices, format_device_info, _get_cpu_info, _get_memory_gb, _get_physical_cores


class TestDeviceScanner:
    """Tests for the device scanner module."""

    def test_scan_devices_returns_dict(self):
        info = scan_devices()
        assert isinstance(info, dict)

    def test_scan_devices_has_required_keys(self):
        info = scan_devices()
        required_keys = [
            "platform", "python", "cpu", "cpu_cores_physical",
            "cpu_cores_logical", "memory_gb", "cuda_available",
            "cuda_version", "gpu", "gpu_memory_gb",
        ]
        for key in required_keys:
            assert key in info, f"Missing key: {key}"

    def test_cpu_info_is_string(self):
        cpu = _get_cpu_info()
        assert isinstance(cpu, str)
        assert len(cpu) > 0

    def test_memory_gb_is_positive(self):
        mem = _get_memory_gb()
        assert mem > 0

    def test_physical_cores_is_positive(self):
        cores = _get_physical_cores()
        assert cores > 0

    def test_cpu_cores_logical_matches_os(self):
        import os
        info = scan_devices()
        assert info["cpu_cores_logical"] == os.cpu_count()

    def test_cuda_available_is_bool(self):
        info = scan_devices()
        assert isinstance(info["cuda_available"], bool)

    def test_cuda_version_when_available(self):
        info = scan_devices()
        if info["cuda_available"]:
            assert info["cuda_version"] is not None
            assert isinstance(info["cuda_version"], int)
            assert info["gpu_memory_gb"] is not None
            assert info["gpu_memory_gb"] > 0


class TestFormatDeviceInfo:
    """Tests for the format_device_info function."""

    def test_returns_string(self):
        info = scan_devices()
        result = format_device_info(info)
        assert isinstance(result, str)

    def test_contains_cpu_info(self):
        info = scan_devices()
        result = format_device_info(info)
        assert info["cpu"] in result

    def test_contains_core_count(self):
        info = scan_devices()
        result = format_device_info(info)
        assert "cores" in result

    def test_contains_ram(self):
        info = scan_devices()
        result = format_device_info(info)
        assert "GB RAM" in result

    def test_comma_delimited(self):
        info = scan_devices()
        result = format_device_info(info)
        assert ", " in result
        parts = result.split(", ")
        assert len(parts) >= 3

    def test_handles_bytes_gpu_name(self):
        info = {
            "cpu": "Test CPU",
            "cpu_cores_logical": 4,
            "memory_gb": 16.0,
            "cuda_available": True,
            "cuda_version": 12060,
            "gpu": b"NVIDIA Test GPU",
            "gpu_memory_gb": 8.0,
        }
        result = format_device_info(info)
        assert "NVIDIA Test GPU" in result

    def test_no_cuda(self):
        info = {
            "cpu": "Test CPU",
            "cpu_cores_logical": 4,
            "memory_gb": 16.0,
            "cuda_available": False,
            "cuda_version": None,
            "gpu": None,
            "gpu_memory_gb": None,
        }
        result = format_device_info(info)
        assert "No CUDA" in result
