# Generated by Claude Opus 4 on 2026-05-05
from dataclasses import dataclass


@dataclass
class MandelbrotConfig:
    xmin: float = -2.0
    xmax: float = 1.0
    ymin: float = -1.5
    ymax: float = 1.5
    width: int = 1024
    height: int = 1024
    max_iter: int = 100
    chunk_size: int = 128
    num_processes: int | None = None
