# Generated by Claude Opus 4 on 2026-05-07
import warnings

import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator

try:
    from numba import cuda
    _CUDA_AVAILABLE = cuda.is_available()
except (ImportError, Exception):
    _CUDA_AVAILABLE = False


@cuda.jit
def _mandelbrot_kernel(xmin, xmax, ymin, ymax, width, height, max_iter, output):
    """CUDA kernel for Mandelbrot set computation.

    Each thread computes one pixel. The thread maps its global (x, y) index
    to a point in the complex plane and iterates z = z^2 + c until escape
    or max_iter is reached.

    Parameters
    ----------
    xmin, xmax, ymin, ymax : float
        Complex plane bounds.
    width, height : int
        Image dimensions.
    max_iter : int
        Maximum iteration count.
    output : 2D device array
        Output array to write iteration counts into.
    """
    col, row = cuda.grid(2)

    if row < height and col < width:
        # Map pixel to complex plane (linspace-style: endpoints inclusive)
        x_step = (xmax - xmin) / max(1, width - 1)
        y_step = (ymax - ymin) / max(1, height - 1)
        real = xmin + col * x_step
        imag = ymin + row * y_step

        c_real = real
        c_imag = imag
        z_real = 0.0
        z_imag = 0.0

        iteration = 0
        for i in range(max_iter):
            z_real_sq = z_real * z_real
            z_imag_sq = z_imag * z_imag

            if z_real_sq + z_imag_sq > 4.0:
                break

            z_imag = 2.0 * z_real * z_imag + c_imag
            z_real = z_real_sq - z_imag_sq + c_real
            iteration = i + 1

        output[row, col] = iteration


class CudaCalculator(MandelbrotCalculator):
    """Mandelbrot calculator using Numba @cuda.jit kernel.

    Launches a 2D CUDA grid where each thread computes one pixel.
    Block size (threads per block) is configurable for performance analysis.

    Block Size / Warp-Size Analysis
    -------------------------------
    NVIDIA GPUs execute threads in warps of 32. The block size (threads per
    block) should be a multiple of 32 to avoid wasting execution slots:

    - Block sizes that are NOT warp multiples (e.g., 20×20=400 threads) leave
      partial warps with idle threads, reducing SM occupancy.
    - Block sizes that ARE warp multiples (e.g., 16×16=256, 32×8=256) ensure
      full warp utilization.
    - The optimal block size depends on register pressure and shared memory
      usage. For this compute-bound kernel (no shared memory), 16×16 or 32×8
      typically perform best.
    - Larger blocks (32×32=1024) can reduce occupancy if register usage per
      thread is high, since fewer blocks fit per SM.
    - The default 16×16 (256 threads/block) is a good general choice: it's a
      warp multiple, allows high occupancy, and maps naturally to 2D grids.
    """

    # Default block size: 16x16 = 256 threads (8 full warps per block)
    DEFAULT_BLOCK_SIZE = (16, 16)

    def __init__(self, config: MandelbrotConfig, block_size: tuple[int, int] | None = None):
        """Initialise the CUDA JIT calculator.

        Parameters
        ----------
        config : MandelbrotConfig
            Mandelbrot set configuration.
        block_size : tuple[int, int], optional
            Threads per block as (x, y). Defaults to (16, 16).
            Must be a 2D tuple where x*y <= 1024 (hardware limit).
        """
        super().__init__(config)
        self._cuda_available = _CUDA_AVAILABLE
        self.block_size = block_size or self.DEFAULT_BLOCK_SIZE

        if not self._cuda_available:
            warnings.warn(
                "Numba CUDA not available. CudaCalculator.calculate() will fail.",
                RuntimeWarning,
                stacklevel=2,
            )

    def calculate(self) -> np.ndarray:
        """Compute the Mandelbrot set using a CUDA JIT kernel.

        Launches a 2D grid of threads. Each thread computes one pixel's
        iteration count. The grid dimensions are computed from the image
        size and block size.

        Returns
        -------
        np.ndarray
            2D int array of shape (height, width) with iteration counts.
        """
        if not self._cuda_available:
            raise RuntimeError("Numba CUDA not available.")

        cfg = self.config

        # Allocate output on device
        output_device = cuda.device_array((cfg.height, cfg.width), dtype=np.int32)

        # Compute grid dimensions: ceil(dimension / block_dim)
        bx, by = self.block_size
        grid_x = (cfg.width + bx - 1) // bx
        grid_y = (cfg.height + by - 1) // by
        grid_size = (grid_x, grid_y)

        # Launch kernel
        _mandelbrot_kernel[grid_size, self.block_size](
            cfg.xmin, cfg.xmax, cfg.ymin, cfg.ymax,
            cfg.width, cfg.height, cfg.max_iter,
            output_device,
        )

        # Copy result back to host
        result = output_device.copy_to_host()

        return result
