# Generated by Claude Opus 4 on 2026-05-05
from abc import ABC, abstractmethod

import numpy as np

from .config import MandelbrotConfig


class MandelbrotCalculator(ABC):
    """Base class for all Mandelbrot set calculators."""

    def __init__(self, config: MandelbrotConfig):
        self.config = config

    @abstractmethod
    def calculate(self) -> np.ndarray:
        """
        Compute the Mandelbrot set and return a 2D array of iteration counts.
        Shape: (config.height, config.width), dtype: int
        """
        ...
