# Generated by Claude Opus 4 on 2026-05-06
import warnings

import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator

try:
    import cupy as cp
    _CUPY_AVAILABLE = True
except (ImportError, Exception):
    _CUPY_AVAILABLE = False


class CupyCalculator(MandelbrotCalculator):
    """Vectorized Mandelbrot calculator using CuPy (GPU-accelerated NumPy).

    Same algorithm as NumpyCalculator but runs on the GPU via CuPy arrays.
    """

    def __init__(self, config: MandelbrotConfig):
        """Initialise the CuPy calculator.

        Parameters
        ----------
        config : MandelbrotConfig
            Mandelbrot set configuration.
        """
        super().__init__(config)
        self._cuda_available = _CUPY_AVAILABLE

        if not self._cuda_available:
            warnings.warn(
                "CuPy/CUDA not available. CupyCalculator.calculate() will fail.",
                RuntimeWarning,
                stacklevel=2,
            )

    def calculate(self) -> np.ndarray:
        """Compute the Mandelbrot set on the GPU using CuPy vectorized ops.

        Returns
        -------
        np.ndarray
            2D int array of shape (height, width) with iteration counts.
        """
        if not self._cuda_available:
            raise RuntimeError("CuPy/CUDA not available.")

        cfg = self.config

        x = cp.linspace(cfg.xmin, cfg.xmax, cfg.width)
        y = cp.linspace(cfg.ymin, cfg.ymax, cfg.height)
        X, Y = cp.meshgrid(x, y)
        c = X + 1j * Y

        z = cp.zeros_like(c)
        output = cp.zeros(c.shape, dtype=cp.int32)

        for n in range(cfg.max_iter):
            mask = cp.abs(z) <= 2
            z[mask] = z[mask] ** 2 + c[mask]
            output[mask] = n + 1

        return cp.asnumpy(output)

