# Generated by Claude Opus 4 on 2026-05-05
import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


class CudaCalculator(MandelbrotCalculator):
    """CUDA/GPU Mandelbrot calculator (stub — requires PyCUDA or Numba CUDA)."""

    def calculate(self) -> np.ndarray:
        raise NotImplementedError("CUDA calculator not yet implemented")
