# Generated by Claude Opus 4 on 2026-05-06
import numpy as np
import dask.array as da

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


def _mandelbrot_chunk(c_chunk: np.ndarray, max_iter: int) -> np.ndarray:
    """Compute Mandelbrot iteration counts for a chunk of the complex plane.

    Uses the same vectorized NumPy algorithm as NumpyCalculator but operates
    on a single chunk passed by Dask's map_blocks.

    Parameters
    ----------
    c_chunk : np.ndarray
        2D array of complex numbers representing a tile of the complex plane.
    max_iter : int
        Maximum number of iterations before considering a point in the set.

    Returns
    -------
    np.ndarray
        2D int32 array of iteration counts with the same shape as c_chunk.
    """
    z = np.zeros_like(c_chunk)
    output = np.zeros(c_chunk.shape, dtype=np.int32)
    for n in range(max_iter):
        mask = np.abs(z) <= 2
        if not mask.any():
            break
        z[mask] = z[mask] ** 2 + c_chunk[mask]
        output[mask] = n + 1
    return output


class DaskCalculator(MandelbrotCalculator):
    """Dask-based Mandelbrot calculator using map_blocks for chunk parallelism.

    Builds the complex-plane grid with NumPy, wraps it in a Dask array
    chunked by config.chunk_size, and uses map_blocks to distribute
    computation across Dask's thread/process scheduler.
    """

    def calculate(self) -> np.ndarray:
        """Compute the Mandelbrot set using Dask array map_blocks.

        The complex plane is split into chunks of size (chunk_size x chunk_size).
        Each chunk is processed independently by _mandelbrot_chunk via Dask's
        local scheduler (synchronous by default, or threaded/multiprocess
        depending on dask configuration).

        Returns
        -------
        np.ndarray
            2D integer array of shape (height, width) containing
            the escape iteration count for each pixel.
        """
        cfg = self.config

        x = np.linspace(cfg.xmin, cfg.xmax, cfg.width)
        y = np.linspace(cfg.ymin, cfg.ymax, cfg.height)
        X, Y = np.meshgrid(x, y)
        c = (X + 1j * Y).astype(np.complex128)

        c_dask = da.from_array(c, chunks=(cfg.chunk_size, cfg.chunk_size))
        result = da.map_blocks(
            _mandelbrot_chunk, c_dask, dtype=np.int32, max_iter=cfg.max_iter
        )

        return result.compute()
