# Generated by Claude Opus 4 on 2026-05-05
import multiprocessing as mp

import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


def _generate_chunks(cfg: MandelbrotConfig):
    """Generate chunk metadata with bounds and pixel positions."""
    chunk_w = cfg.chunk_size
    chunk_h = cfg.chunk_size
    # Use (n-1) divisor to match np.linspace endpoint semantics
    x_scale = 0 if cfg.width == 1 else (cfg.xmax - cfg.xmin) / (cfg.width - 1)
    y_scale = 0 if cfg.height == 1 else (cfg.ymax - cfg.ymin) / (cfg.height - 1)

    chunks = []
    for r in range(0, cfg.height, chunk_h):
        for c in range(0, cfg.width, chunk_w):
            c_width = min(chunk_w, cfg.width - c)
            c_height = min(chunk_h, cfg.height - r)

            # Bounds based on first and last pixel index in this chunk
            c_xmin = cfg.xmin + c * x_scale
            c_xmax = cfg.xmin + (c + c_width - 1) * x_scale
            c_ymin = cfg.ymin + r * y_scale
            c_ymax = cfg.ymin + (r + c_height - 1) * y_scale

            chunks.append((c, r, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height))

    return chunks


def _process_chunk(args):
    """Compute a single chunk by reusing NumpyCalculator."""
    from .mb_numpy_calculator import NumpyCalculator

    start_col, start_row, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height, max_iter = args

    chunk_cfg = MandelbrotConfig(
        xmin=c_xmin, xmax=c_xmax,
        ymin=c_ymin, ymax=c_ymax,
        width=c_width, height=c_height,
        max_iter=max_iter,
    )
    result = NumpyCalculator(chunk_cfg).calculate()

    return (start_col, start_row, result)


class MultiprocessCalculator(MandelbrotCalculator):
    """Multiprocessing chunked Mandelbrot calculator (NumPy per chunk)."""

    def __init__(self, config: MandelbrotConfig, num_processes: int | None = None, chunk_size: int | None = None):
        super().__init__(config)
        self.num_processes = num_processes or config.num_processes or mp.cpu_count()
        self.chunk_size = chunk_size or config.chunk_size

    def calculate(self) -> np.ndarray:
        cfg = self.config
        # Override chunk_size for chunk generation
        cfg_for_chunks = MandelbrotConfig(
            xmin=cfg.xmin, xmax=cfg.xmax,
            ymin=cfg.ymin, ymax=cfg.ymax,
            width=cfg.width, height=cfg.height,
            max_iter=cfg.max_iter,
            chunk_size=self.chunk_size,
        )

        chunks = _generate_chunks(cfg_for_chunks)
        work_items = [(*chunk, cfg.max_iter) for chunk in chunks]

        with mp.Pool(processes=self.num_processes) as pool:
            results = pool.map(_process_chunk, work_items)

        final_image = np.zeros((cfg.height, cfg.width), dtype=int)
        for start_col, start_row, chunk_result in results:
            h, w = chunk_result.shape
            final_image[start_row:start_row + h, start_col:start_col + w] = chunk_result

        return final_image
