# Generated by Claude Opus 4 on 2026-05-05
import logging
import multiprocessing as mp

import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator

logger = logging.getLogger(__name__)


def _generate_chunks(cfg: MandelbrotConfig):
    """Generate chunk metadata with bounds and pixel positions.

    Splits the full image into rectangular tiles based on cfg.chunk_size.
    Each chunk contains the pixel offsets and corresponding complex-plane
    bounds needed to compute that tile independently.

    Parameters
    ----------
    cfg : MandelbrotConfig
        Configuration with width, height, chunk_size, and plane bounds.

    Returns
    -------
    list[tuple]
        Each element is (start_col, start_row, c_xmin, c_xmax, c_ymin,
        c_ymax, c_width, c_height) describing one chunk's position
        and complex-plane extent.
    """
    chunk_w = cfg.chunk_size
    chunk_h = cfg.chunk_size
    # Use (n-1) divisor to match np.linspace endpoint semantics
    x_scale = 0 if cfg.width == 1 else (cfg.xmax - cfg.xmin) / (cfg.width - 1)
    y_scale = 0 if cfg.height == 1 else (cfg.ymax - cfg.ymin) / (cfg.height - 1)

    chunks = []
    for r in range(0, cfg.height, chunk_h):
        for c in range(0, cfg.width, chunk_w):
            c_width = min(chunk_w, cfg.width - c)
            c_height = min(chunk_h, cfg.height - r)

            # Bounds based on first and last pixel index in this chunk
            c_xmin = cfg.xmin + c * x_scale
            c_xmax = cfg.xmin + (c + c_width - 1) * x_scale
            c_ymin = cfg.ymin + r * y_scale
            c_ymax = cfg.ymin + (r + c_height - 1) * y_scale

            chunks.append((c, r, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height))

    return chunks


def _get_calculator_class(name: str):
    """Resolve a calculator name to its class (import inside function for pickling)."""
    if name == "numpy":
        from .mb_numpy_calculator import NumpyCalculator
        return NumpyCalculator
    elif name == "native":
        from .mb_native_calculator import NativeCalculator
        return NativeCalculator
    elif name == "numba":
        from .mb_numba_calculator import NumbaCalculator
        return NumbaCalculator
    else:
        raise ValueError(f"Unknown base calculator: '{name}'. Available: native, numpy, numba")


def _process_chunk(args):
    """Compute a single chunk by delegating to the configured base calculator.

    Creates a MandelbrotConfig scoped to the chunk's bounds and resolution,
    then runs the chosen calculator on it.

    Parameters
    ----------
    args : tuple
        (start_col, start_row, c_xmin, c_xmax, c_ymin, c_ymax,
        c_width, c_height, max_iter, base_calculator).

    Returns
    -------
    tuple
        (start_col, start_row, result_array) where result_array is a
        2D np.ndarray of iteration counts for the chunk.
    """
    start_col, start_row, c_xmin, c_xmax, c_ymin, c_ymax, c_width, c_height, max_iter, base_calculator = args

    chunk_cfg = MandelbrotConfig(
        xmin=c_xmin, xmax=c_xmax,
        ymin=c_ymin, ymax=c_ymax,
        width=c_width, height=c_height,
        max_iter=max_iter,
    )
    calc_cls = _get_calculator_class(base_calculator)
    result = calc_cls(chunk_cfg).calculate()

    return (start_col, start_row, result)


class MultiprocessCalculator(MandelbrotCalculator):
    """Multiprocessing chunked Mandelbrot calculator with configurable base."""

    def __init__(self, config: MandelbrotConfig, num_processes: int | None = None,
                 chunk_size: int | None = None, base_calculator: str = "numpy"):
        """Initialise the multiprocess calculator.

        Parameters
        ----------
        config : MandelbrotConfig
            Configuration with plane bounds, resolution, and max_iter.
        num_processes : int or None
            Number of worker processes. Defaults to config value
            or system CPU count.
        chunk_size : int or None
            Tile size (pixels) for splitting the image. Defaults to
            config.chunk_size.
        base_calculator : str
            Which calculator to use per chunk. One of:
            "native", "numpy", "numba". Defaults to "numpy".
        """
        super().__init__(config)
        self.num_processes = num_processes or config.num_processes or mp.cpu_count()
        self.chunk_size = chunk_size or config.chunk_size
        self.base_calculator = base_calculator

    def calculate(self) -> np.ndarray:
        """Compute the Mandelbrot set using multiprocessing.

        Splits the image into chunks, distributes them across a process pool,
        and reassembles the results into the final image.

        Returns
        -------
        np.ndarray
            2D integer array of shape (height, width) containing
            the escape iteration count for each pixel.
        """
        cfg = self.config
        # Override chunk_size for chunk generation
        cfg_for_chunks = MandelbrotConfig(
            xmin=cfg.xmin, xmax=cfg.xmax,
            ymin=cfg.ymin, ymax=cfg.ymax,
            width=cfg.width, height=cfg.height,
            max_iter=cfg.max_iter,
            chunk_size=self.chunk_size,
        )

        chunks = _generate_chunks(cfg_for_chunks)
        work_items = [(*chunk, cfg.max_iter, self.base_calculator) for chunk in chunks]

        logger.info("Starting MultiprocessCalculator with %d processes, chunk size %d, "
                    "base calculator '%s', total chunks: %d",
                    self.num_processes, self.chunk_size, self.base_calculator, len(chunks))
        logger.debug(
            "MultiprocessCalculator: resolution=%dx%d, base=%s, "
            "processes=%d, chunk_size=%d, total_chunks=%d",
            cfg.width, cfg.height, self.base_calculator,
            self.num_processes, self.chunk_size, len(chunks),
        )

        with mp.Pool(processes=self.num_processes) as pool:
            results = pool.map(_process_chunk, work_items)

        final_image = np.zeros((cfg.height, cfg.width), dtype=int)
        for start_col, start_row, chunk_result in results:
            h, w = chunk_result.shape
            final_image[start_row:start_row + h, start_col:start_col + w] = chunk_result

        return final_image
