# Generated by Claude Opus 4 on 2026-05-05
import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


class NativeCalculator(MandelbrotCalculator):
    """Pure Python nested-loop Mandelbrot calculator."""

    def calculate(self) -> np.ndarray:
        cfg = self.config
        mb_set = np.zeros((cfg.height, cfg.width), dtype=int)

        for y in range(cfg.height):
            p_y = cfg.ymin if cfg.height == 1 else cfg.ymin + (y / (cfg.height - 1)) * (cfg.ymax - cfg.ymin)

            for x in range(cfg.width):
                p_x = cfg.xmin if cfg.width == 1 else cfg.xmin + (x / (cfg.width - 1)) * (cfg.xmax - cfg.xmin)
                c = p_x + 1j * p_y

                z = 0
                n = 0
                while abs(z) <= 2 and n < cfg.max_iter:
                    z = z ** 2 + c
                    n += 1

                mb_set[y, x] = n

        return mb_set
