# Generated by Claude Opus 4 on 2026-05-05
import numpy as np
from numba import jit

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


@jit(nopython=True)
def _numba_compute(xmin, xmax, ymin, ymax, width, height, max_iter):
    """JIT-compiled Mandelbrot kernel."""
    mb_set = np.zeros((height, width), dtype=np.int64)

    for y in range(height):
        p_y = ymin if height == 1 else ymin + (y / (height - 1)) * (ymax - ymin)

        for x in range(width):
            p_x = xmin if width == 1 else xmin + (x / (width - 1)) * (xmax - xmin)
            c = p_x + 1j * p_y

            z = 0 + 0j
            n = 0
            while abs(z) <= 2 and n < max_iter:
                z = z * z + c
                n += 1

            mb_set[y, x] = n

    return mb_set


class NumbaCalculator(MandelbrotCalculator):
    """Numba JIT-compiled Mandelbrot calculator."""

    def calculate(self) -> np.ndarray:
        cfg = self.config
        return _numba_compute(
            cfg.xmin, cfg.xmax, cfg.ymin, cfg.ymax,
            cfg.width, cfg.height, cfg.max_iter
        )
