# Generated by Claude Opus 4 on 2026-05-05
import numpy as np

from .config import MandelbrotConfig
from .mb_calculator import MandelbrotCalculator


class NumpyCalculator(MandelbrotCalculator):
    """Vectorized NumPy Mandelbrot calculator."""

    def calculate(self) -> np.ndarray:
        cfg = self.config

        x = np.linspace(cfg.xmin, cfg.xmax, cfg.width)
        y = np.linspace(cfg.ymin, cfg.ymax, cfg.height)
        X, Y = np.meshgrid(x, y)
        c = X + 1j * Y

        z = np.zeros_like(c)
        output = np.zeros(c.shape, dtype=int)

        for n in range(cfg.max_iter):
            mask = np.abs(z) <= 2
            z[mask] = z[mask] ** 2 + c[mask]
            output[mask] = n + 1

        return output
